from django.contrib.auth.models import User

from .auto_analize_formula import *
from .checkpoint import *
from .diary_meal import *
from .diary_meal_fault import *
from .diary_record import *
from .diary_record_analysis import *
from .gtt_result import *
from .instagram_image import *
from .invitation import *
from .meal_component import *
from .meal_fault import *
from .meal_notice import *
from .meal_product import *
from .meal_product_moderation import *
from .participation_goal import *
from .profile import *
from .profile_stat import *
from .srbc_image import *
from .stat_group_history import *
from .subscription import *
from .tariff import *
from .tariff_group import *
from .tech_duty import *
from .user_book_mark import *
from .user_note import *
from .user_report import *
from .wave import *
