# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 06:38


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_remove_tgpost_wave'),
        ('srbc', '0107_invitation_communication_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wave',
            name='tg_channel_id',
        ),
        migrations.RemoveField(
            model_name='wave',
            name='tg_channel_slug',
        ),
        migrations.AddField(
            model_name='wave',
            name='starting_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.TGChat'),
        ),
    ]
