# Generated by Django 3.0.6 on 2020-05-30 12:18

from django.db import migrations, models
import django.db.models.deletion
import shared.models


class Migration(migrations.Migration):

    replaces = [('srbc', '0109_profiletwoweekstat'), ('srbc', '0110_auto_20171202_1700'), ('srbc', '0111_auto_20171202_1710'), ('srbc', '0112_auto_20171202_1715'), ('srbc', '0113_auto_20171228_0051'), ('srbc', '0114_auto_20180106_1955'), ('srbc', '0115_profile_admission_status'), ('srbc', '0116_auto_20180108_1443'), ('srbc', '0117_auto_20180111_1323'), ('srbc', '0118_auto_20180113_0510'), ('srbc', '0119_auto_20180118_1145'), ('srbc', '0120_auto_20180118_1653'), ('srbc', '0121_auto_20180120_0907')]

    dependencies = [
        ('srbc', '0108_auto_20171116_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTwoWeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('trueweight_start', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('trueweight_end', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight_start', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight_end', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('steps_days', models.PositiveIntegerField(blank=True, null=True)),
                ('steps_ok_days', models.PositiveIntegerField(blank=True, null=True)),
                ('overcalory_days', models.PositiveIntegerField(blank=True, null=True)),
                ('ooc_days', models.PositiveIntegerField(blank=True, null=True)),
                ('faulty_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meals_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meals_bad_days', models.PositiveIntegerField(blank=True, null=True)),
                ('alco_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile_2week_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoAnalizeFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['date_added'], name='srbc_userno_date_ad_9c665d_idx'),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['is_published'], name='srbc_userno_is_publ_7f7b38_idx'),
        ),
        migrations.AddIndex(
            model_name='autoanalizeformula',
            index=models.Index(fields=['code'], name='srbc_autoan_code_9c4b4d_idx'),
        ),
        migrations.AddField(
            model_name='autoanalizeformula',
            name='attention_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='autoanalizeformula',
            index=models.Index(fields=['attention_required'], name='srbc_autoan_attenti_c3204b_idx'),
        ),
        migrations.AlterField(
            model_name='autoanalizeformula',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='widgets_display',
            field=shared.models.ChoiceArrayField(base_field=models.CharField(choices=[(b'NOTES', 'Персональные рекомендации'), (b'CALENDAR', 'Календарь данных'), (b'MEETINGS', 'Последние митинги'), (b'ALARM', 'Алярм'), (b'CHARTS', 'Графики с данными')], max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='label',
            field=models.CharField(choices=[(b'DOC', 'Док / Обследования'), (b'PZDC', 'Кризис'), (b'IG', 'Анализ ИГ'), (b'CHAT', 'Корректировка рациона'), (b'NB', 'Служебная заметка')], max_length=100),
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='meal_last_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admission_status',
            field=models.CharField(blank=True, choices=[(b'NOT_STARTED', 'Не дошел'), (b'IN_PROGRESS', 'В процессе'), (b'DONE', 'Завершил'), (b'PASSED', 'Проверено, всё ок'), (b'FAILED', 'Проверено, завалил'), (b'REJECTED', 'Отказано'), (b'ACCEPTED', 'Принят')], default=b'NOT_STARTED', max_length=100),
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='meal_status',
            field=models.CharField(choices=[(b'NOT_READY', 'Ожидает заполнения'), (b'PENDING', 'Ожидает оцифровки'), (b'VALIDATION', 'Ожидает проверки оцифровки'), (b'FEEDBACK', 'Ожидает ответа'), (b'DONE', 'Оцифрован'), (b'NA_WARN', 'Нет данных, предупреждён'), (b'NA', 'Нет данных'), (b'FAKE', 'Данные недостоверны')], default=b'NOT_READY', max_length=50),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='label',
            field=models.CharField(choices=[(b'DOC', 'Док / Обследования'), (b'PZDC', 'Кризис'), (b'IG', 'Анализ ИГ'), (b'CHAT', 'Корректировка рациона'), (b'NB', 'Служебная заметка'), (b'ORG', 'Организационные вопросы')], max_length=100),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('mailchimp_group_id', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='checkpointrecord',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='application',
            name='email_status',
            field=models.CharField(blank=True, choices=[(b'NEW', 'Новый'), (b'PENDING', 'Ожидает подтверждения'), (b'APPROVED', 'Подтвержден'), (b'DISCONNECTED', 'Отписан')], default=b'NEW', max_length=25),
        ),
        migrations.AddField(
            model_name='checkpointrecord',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkpointrecord',
            name='rejection_reasons',
            field=shared.models.ChoiceArrayField(base_field=models.CharField(choices=[(b'CLOTHES', b'\xd0\x9d\xd0\xb5\xd1\x83\xd0\xb4\xd0\xb0\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbe\xd0\xb4\xd0\xb5\xd0\xb6\xd0\xb4\xd0\xb0 (\xd0\xbb\xd0\xb5\xd0\xb3\xd0\xb3\xd0\xb8\xd0\xbd\xd1\x81\xd1\x8b, \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xba\xd0\xb8, \xd1\x81\xd0\xbb\xd0\xb8\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xba\xd1\x83\xd0\xbf\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x82.\xd0\xb4.)'), (b'CUTOFF', b'\xd0\x9e\xd0\xb1\xd1\x80\xd0\xb5\xd0\xb7\xd0\xb0\xd0\xbd\xd1\x8b \xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb0 (\xd0\xbd\xd0\xb5\xd1\x82 \xd0\xbd\xd0\xbe\xd0\xb3-\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd1\x8b)'), (b'ANGLE', b'\xd0\x9d\xd0\xb5\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x80\xd0\xb0\xd0\xba\xd1\x83\xd1\x80\xd1\x81 (\xd1\x81\xd0\xb2\xd0\xb5\xd1\x80\xd1\x85\xd1\x83 \xd0\xb2\xd0\xbd\xd0\xb8\xd0\xb7 \xd0\xb8\xd0\xbb\xd0\xb8 \xd1\x81\xd0\xbd\xd0\xb8\xd0\xb7\xd1\x83 \xd0\xb2\xd0\xb2\xd0\xb5\xd1\x80\xd1\x85)'), (b'POSE', b'\xd0\x9d\xd0\xb5\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd0\xb7\xd0\xb0 (\xd1\x82\xd1\x80\xd0\xb8 \xd1\x87\xd0\xb5\xd1\x82\xd0\xb2\xd0\xb5\xd1\x80\xd1\x82\xd0\xb8 \xd0\xb2\xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe \xd0\xb0\xd0\xbd\xd1\x84\xd0\xb0\xd1\x81 \xd0\xb8 \xd1\x82.\xd0\xbf., \xd1\x80\xd1\x83\xd0\xba\xd0\xb8 \xd0\xb7\xd0\xb0\xd0\xba\xd1\x80\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x8e\xd1\x82 \xd0\xb8\xd0\xb7\xd0\xb3\xd0\xb8\xd0\xb1 \xd1\x81\xd0\xbf\xd0\xb8\xd0\xbd\xd1\x8b)'), (b'LIGHT', b'\xd0\x9d\xd0\xb5\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd0\xbe\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbe\xd1\x81\xd0\xb2\xd0\xb5\xd1\x89\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c-\xd0\xba\xd0\xbe\xd0\xbd\xd1\x82\xd1\x80\xd0\xb0\xd1\x81\xd1\x82\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c (\xd1\x81\xd0\xbd\xd1\x8f\xd1\x82\xd0\xbe \xd0\xb2 \xd1\x82\xd0\xb5\xd0\xbc\xd0\xbd\xd0\xbe\xd1\x82\xd0\xb5, \xd1\x81\xd0\xbd\xd1\x8f\xd1\x82\xd0\xbe \xd0\xbf\xd1\x80\xd0\xbe\xd1\x82\xd0\xb8\xd0\xb2 \xd1\x81\xd0\xb2\xd0\xb5\xd1\x82\xd0\xb0)'), (b'BACKGROUND', b'\xd0\x9d\xd0\xb5\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x84\xd0\xbe\xd0\xbd (\xd0\xbe\xd1\x87\xd0\xb5\xd0\xbd\xd1\x8c \xd0\xbf\xd0\xb5\xd1\x81\xd1\x82\xd1\x80\xd1\x8b\xd0\xb9)'), (b'BLUR', b'\xd0\xa4\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd0\xb8 \xd0\xbd\xd0\xb5 \xd0\xb2 \xd1\x84\xd0\xbe\xd0\xba\xd1\x83\xd1\x81\xd0\xb5 (\xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x80\xd0\xb0\xd0\xb7\xd0\xbc\xd1\x8b\xd1\x82\xd0\xbe)')], max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='application',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.Campaign'),
        ),
    ]
