# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 12:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('srbc', '0121_auto_20180120_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Campaign'),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
