# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-25 13:42


from django.db import migrations, models


def update_self_meal_review(apps, schema_editor):
    DiaryRecord = apps.get_model('srbc', 'DiaryRecord')
    for diary in DiaryRecord.objects.filter(user__profile__is_self_meal_formula=True).exclude(
            meal_status__in=['DONE', 'NA', 'FAKE', 'VALIDATION', 'PENDING', 'FEEDBACK']).all():
        diary.meal_self_review = True
        diary.save(update_fields=['meal_self_review'])


def clear_self_meal_review(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('srbc', '0188_mealproduct_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='meal_self_review',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_self_meal_review, clear_self_meal_review),
    ]
