# Generated by Django 3.0.6 on 2020-06-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0191_auto_20200530_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymeal',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals_data', to='srbc.DiaryRecord'),
        ),
    ]
