# Generated by Django 3.0.6 on 2020-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0192_auto_20200602_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='fiber_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Клетчаточный эквивалент (на 100г)'),
        ),
    ]
