# Generated by Django 3.0.6 on 2020-08-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0194_auto_20200730_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealproduct',
            old_name='starch_percent',
            new_name='starch_proxy_percent',
        ),
    ]
