# Generated by Django 3.0.6 on 2020-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0195_auto_20200807_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealproduct',
            old_name='fiber_percent',
            new_name='fiber_proxy_percent',
        ),
        migrations.RenameField(
            model_name='mealproduct',
            old_name='glucose_percent',
            new_name='glucose_proxy_percent',
        ),
        migrations.AddField(
            model_name='mealproduct',
            name='protein_proxy_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Белковый эквивалент (на 100г)'),
        ),
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['is_fast_carbs'], name='srbc_mealpr_is_fast_b00f80_idx'),
        ),
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['is_alco'], name='srbc_mealpr_is_alco_71ae85_idx'),
        ),
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['starch_proxy_percent'], name='srbc_mealpr_starch__381a17_idx'),
        ),
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['fiber_proxy_percent'], name='srbc_mealpr_fiber_p_aebc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['glucose_proxy_percent'], name='srbc_mealpr_glucose_082eda_idx'),
        ),
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['protein_proxy_percent'], name='srbc_mealpr_protein_b19cb4_idx'),
        ),
    ]
