# Generated by Django 3.1 on 2020-10-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0197_auto_20201005_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproducttag',
            name='is_analytical',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='component_type',
            field=models.CharField(blank=True, choices=[('bread', 'Хлеб'), ('fat', 'Жирный продукт'), ('carb', 'Готовые углеводы'), ('rawcarb', 'Сухие углеводы'), ('fatcarb', 'Жирные углеводы'), ('protein', 'Белковый продукт'), ('deadweight', 'Балласт'), ('veg', 'Овощи'), ('carbveg', 'Запасающие овощи'), ('fruit', 'Фрукты'), ('dfruit', 'Сухофрукты'), ('desert', 'Десерт'), ('drink', 'Калорийный напиток'), ('alco', 'Алкоголь'), ('unknown', 'Продукт с неопределенным составом'), ('ufs', 'Продукт сомнительной питательной ценности'), ('mix', 'Сложная смесь')], default=None, max_length=50, null=True, verbose_name='Продукт'),
        ),
        migrations.AddIndex(
            model_name='mealproducttag',
            index=models.Index(fields=['is_analytical'], name='srbc_mealpr_is_anal_781588_idx'),
        ),
    ]
