# Generated by Django 3.1 on 2020-10-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0198_auto_20201022_2046'),
        ('srbc', '0198_mealfault_is_manual'),
    ]

    operations = [
    ]
