# Generated by Django 3.1 on 2020-11-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0199_merge_20201102_1557'),
        ('srbc', '0202_tariffgroup_is_wave'),
    ]

    operations = [
    ]
