# Generated by Django 3.1 on 2020-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0204_auto_20201109_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='adjust_carb_mix_vegs',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
