# Generated by Django 3.1 on 2020-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('srbc', '0205_usernote_mixing_vegetables'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public.srbc_usernote 
            SET adjust_carb_mix_vegs = TRUE
            WHERE adjust_fruits != 'NO'"""
        ),
    ]
