# Generated by Django 3.1 on 2021-01-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0207_auto_20210111_1616'),
        ('srbc', '0206_stripesubscription_stripe_subscription_id'),
    ]

    operations = [
    ]
