# Generated by Django 3.1 on 2021-02-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0209_auto_20210119_1636'),
        ('srbc', '0209_auto_20210126_1622'),
    ]

    operations = [
    ]
