# Generated by Django 3.1 on 2021-02-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0210_merge_20210208_1552'),
        ('srbc', '0208_auto_20210203_1715'),
    ]

    operations = [
    ]
