# Generated by Django 3.1 on 2021-03-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20210211_1641'),
        ('srbc', '0211_merge_20210208_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_tariff_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.tariffhistory'),
        ),
    ]
