# Generated by Django 3.1 on 2021-03-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20210211_1641'),
        ('srbc', '0212_profile_active_tariff_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_tariff_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_next', to='crm.tariffhistory'),
        ),
    ]
