# Generated by Django 3.1.7 on 2021-08-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0215_auto_20210608_1532'),
        ('srbc', '0215_auto_20210705_1129'),
    ]

    operations = [
    ]
