# Generated by Django 3.1.7 on 2021-09-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0216_merge_20210811_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord', name='anlz_mode', field=models.CharField(
                blank=True,
                choices=[('NO', 'Не нужен'),
                         ('ANLZ_AUTO', 'Автоматический анализ'),
                         ('ANLZ_MANUAL', 'Ручной анализ')],
                default=None, max_length=20, null=True),),
        migrations.RunSQL(
            sql='''
                UPDATE public.srbc_diaryrecord
	            SET anlz_mode='ANLZ_MANUAL'
            ''',), ]
