# Generated by Django 3.1.7 on 2021-10-20 12:40

from django.db import migrations, models
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0218_auto_20211012_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymeal',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уровень глюкозы'),
        ),
        migrations.AddField(
            model_name='diarymeal',
            name='glucose_unit',
            field=models.CharField(blank=True, choices=[('mg/dL', 'мг/дл'), ('mmol/L', 'ммоль/л')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diarymeal',
            name='hunger_intensity',
            field=shared.models.IntegerRangeField(blank=True, null=True, verbose_name='Интенсивность голода'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='meal_type',
            field=models.CharField(choices=[('PREBREAKFAST', 'Предзавтрак'), ('BREAKFAST', 'Завтрак'), ('BRUNCH', 'ВЗ'), ('LUNCH', 'Обед'), ('MERIENDA', 'Полдник'), ('DINNER', 'Ужин'), ('SNACK', 'Перекус'), ('SLEEP', 'Дневной сон'), ('HUNGER', 'Чувство голода'), ('BLOOD_GLUCOSE', 'Замер уровня глюкозы в крови')], max_length=25),
        ),
    ]
