# Generated by Django 3.1.7 on 2022-01-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0221_auto_20211228_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffgroup',
            name='analysis_queue',
        ),
        migrations.AddField(
            model_name='tariffgroup',
            name='diary_analyze_mode',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Ручной'), ('AUTO', 'Автоматический'), ('BY_REQUEST', 'По запросу'), ('NO', 'Отсутствует')], max_length=20, null=True),
        ),
    ]
