# Generated by Django 3.1.7 on 2022-01-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0222_auto_20220127_1611'),
        ('srbc', '0222_auto_20220117_1249'),
    ]

    operations = [
    ]
