# Generated by Django 3.1.7 on 2022-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0223_merge_20220201_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
