# Generated by Django 3.1.7 on 2022-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0225_auto_20220220_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='is_weight_accurate',
            field=models.BooleanField(blank=True, null=True, default=True),
        ),
    ]
