# Generated by Django 3.1.7 on 2022-04-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0227_auto_20220317_1716'),
        ('srbc', '0227_auto_20220314_1241'),
    ]

    operations = [
    ]
