# Generated by Django 3.1.7 on 2023-08-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0229_auto_20230728_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdamusSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prodamus_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='prodamus_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='srbc.prodamussubscription'),
        ),
    ]
