# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:48


from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_auto_20170622_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('channel_id', models.CharField(blank=True, max_length=32, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TGMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'NEW', '\u041d\u043e\u0432\u044b\u0439'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0451\u043d'), (b'CANCELED', '\u041e\u0442\u043c\u0435\u043d\u0451\u043d'), (b'ANSWERED', '\u041e\u0442\u0432\u0435\u0447\u0435\u043d')], default=b'NEW', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_to', to='content.Post')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_for', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
