# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_tgmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='TGPost',
        ),
    ]
