# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170622_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='tags',
            field=models.CharField(choices=[(b'QUESTION', '\u0412\u043e\u043f\u0440\u043e\u0441'), (b'FEEDBACK', '\u041e\u0442\u0437\u044b\u0432')], max_length=100),
        ),
    ]
