# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170622_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgmessage',
            old_name='tags',
            new_name='message_type',
        ),
    ]
