# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 07:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170622_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgpost',
            old_name='is_sent',
            new_name='is_posted',
        ),
        migrations.AddField(
            model_name='tgpost',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['created_at'], name='content_tgp_created_72d27d_idx'),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['posted_at'], name='content_tgp_posted__d37d61_idx'),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['channel_id'], name='content_tgp_channel_27ba28_idx'),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['author'], name='content_tgp_author__007dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['is_private'], name='content_tgp_is_priv_d4fa73_idx'),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['is_global'], name='content_tgp_is_glob_7d4d06_idx'),
        ),
        migrations.AddIndex(
            model_name='tgpost',
            index=models.Index(fields=['is_posted'], name='content_tgp_is_post_51b24d_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['created_at'], name='content_tgm_created_c47801_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['status'], name='content_tgm_status_5bf35c_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['author'], name='content_tgm_author__43b7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['assigned'], name='content_tgm_assigne_9c38f9_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['answer'], name='content_tgm_answer__3a4aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['message_type'], name='content_tgm_message_5a8649_idx'),
        ),
    ]
