# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_meetingplayhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingplayhistory',
            name='item',
            field=models.CharField(blank=True, default=b'playlist', max_length=255),
        ),
    ]
