# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_meetingplayhistory_item'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meetingplayhistory',
            index=models.Index(fields=['user'], name='content_mee_user_id_1007e1_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingplayhistory',
            index=models.Index(fields=['meeting'], name='content_mee_meeting_1c52a2_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingplayhistory',
            index=models.Index(fields=['start_time'], name='content_mee_start_t_8dc3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingplayhistory',
            index=models.Index(fields=['ip_addr'], name='content_mee_ip_addr_aea03c_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingplayhistory',
            index=models.Index(fields=['referer_check'], name='content_mee_referer_f7a5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingplayhistory',
            index=models.Index(fields=['item'], name='content_mee_item_10a1eb_idx'),
        ),
    ]
