# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:31


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0013_auto_20170624_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='tg_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
