# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20170625_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgpost',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tgpost',
            name='channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
