# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uid',
            field=models.CharField(default='-', max_length=32),
            preserve_default=False,
        ),
    ]
