# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:55


import content.models
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20170703_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('text', markdownx.models.MarkdownxField(blank=True, default=b'')),
                ('is_published', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='uid',
            field=models.CharField(blank=True, default=content.models.generate_uuid, max_length=32),
        ),
    ]
