# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 14:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_tgpost_image_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['resolved_at'], name='content_tgm_resolve_708f92_idx'),
        ),
        migrations.AddIndex(
            model_name='tgmessage',
            index=models.Index(fields=['resolved_by'], name='content_tgm_resolve_1107e6_idx'),
        ),
    ]
