# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 19:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_tgpost_wave_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgpost',
            old_name='wave_id',
            new_name='wave',
        ),
    ]
