# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 18:58


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0026_auto_20170820_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGParticipantChats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'ALLOWED', b'Allowed'), (b'JOINED', b'Joined'), (b'LEFT', b'Left'), (b'BANNED', b'Banned')], max_length=50)),
                ('status_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='waves',
            field=models.ManyToManyField(to='srbc.Wave'),
        ),
        migrations.AddField(
            model_name='tgparticipantchats',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.TGChat'),
        ),
        migrations.AddField(
            model_name='tgparticipantchats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tgchat',
            name='members',
            field=models.ManyToManyField(through='content.TGParticipantChats', to=settings.AUTH_USER_MODEL),
        ),
    ]
