# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:07


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20170820_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TGParticipantChats',
            new_name='TGChatParticipant',
        ),
    ]
