# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20170820_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgchat',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
