# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20170820_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgchat',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tgchat',
            name='tg_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
