# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 18:14


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20170820_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgpost',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.TGChat'),
        ),
    ]
