# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_tgpost_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgpost',
            old_name='channel_id',
            new_name='tg_chat_id',
        ),
        migrations.RenameField(
            model_name='tgpost',
            old_name='chat',
            new_name='channel',
        ),
    ]
