# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:16


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20170826_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgpost',
            name='tg_chat_id',
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='members',
            field=models.ManyToManyField(related_name='chats', through='content.TGChatParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgchatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='content.TGChat'),
        ),
        migrations.AlterField(
            model_name='tgchatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
