# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 14:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20170826_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgchatparticipant',
            name='status',
            field=models.CharField(blank=True, choices=[(b'ALLOWED', b'Allowed'), (b'JOINED', b'Joined'), (b'LEFT', b'Left'), (b'BANNED', b'Banned')], default=b'ALLOWED', max_length=50),
        ),
    ]
