# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 08:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20170922_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgchat',
            old_name='title',
            new_name='code',
        ),
    ]
