# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 08:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20170922_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgchat',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
