# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 06:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20171116_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgchat',
            name='waves',
        ),
    ]
