# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 06:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_remove_tgchat_waves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgpost',
            name='wave',
        ),
    ]
