# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 21:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20171129_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgchatparticipant',
            name='status',
            field=models.CharField(blank=True, choices=[(b'ALLOWED', b'Allowed'), (b'JOINED', b'Joined'), (b'LEFT', b'Left'), (b'RESTRICTED', b'Restricted'), (b'BANNED', b'Banned')], default=b'ALLOWED', max_length=50),
        ),
    ]
