# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 00:48


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0044_auto_20171228_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('shortcut', models.CharField(blank=True, max_length=4, null=True)),
                ('question_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('question_text', models.TextField(blank=True)),
                ('category', models.CharField(choices=[(b'GENERAL', '#\u0432\u043e\u043f\u0440\u043e\u0441'), (b'IG', '#\u0441\u043c\u0435\u043d\u0430\u043d\u0438\u043a\u0430'), (b'MEETING', '#\u0432\u043e\u043f\u0440\u043e\u0441\u044b\u043a\u043c\u0438\u0442\u0438\u043d\u0433\u0443'), (b'DOC', '#\u0434\u043e\u043a')], max_length=50)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answered_time', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_questions_replies_by', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_questions_by', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_questions', to='content.TGChat')),
            ],
        ),
    ]
