# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 00:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_chatquestion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['category'], name='content_cha_categor_e47ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['shortcut'], name='content_cha_shortcu_648830_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['is_answered'], name='content_cha_is_answ_0af3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['chat'], name='content_cha_chat_id_89519c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['message_id'], name='content_cha_message_cb24cd_idx'),
        ),
    ]
