# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 09:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_auto_20171228_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgchat',
            name='is_moderated',
            field=models.BooleanField(default=True),
        ),
    ]
