# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 09:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_tgchat_is_moderated'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tgchat',
            index=models.Index(fields=['code'], name='content_tgc_code_8fe06f_idx'),
        ),
        migrations.AddIndex(
            model_name='tgchat',
            index=models.Index(fields=['tg_id'], name='content_tgc_tg_id_12fe51_idx'),
        ),
        migrations.AddIndex(
            model_name='tgchat',
            index=models.Index(fields=['is_active'], name='content_tgc_is_acti_f708a5_idx'),
        ),
        migrations.AddIndex(
            model_name='tgchat',
            index=models.Index(fields=['is_main'], name='content_tgc_is_main_79471d_idx'),
        ),
        migrations.AddIndex(
            model_name='tgchat',
            index=models.Index(fields=['chat_type'], name='content_tgc_chat_ty_9bfb91_idx'),
        ),
    ]
