# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 16:55


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0049_auto_20171228_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField()),
                ('is_active', models.BooleanField(default=False)),
                ('answer_ok', models.BooleanField(default=False)),
                ('answer_sweet', models.BooleanField(default=False)),
                ('answer_interval', models.BooleanField(default=False)),
                ('answer_protein', models.BooleanField(default=False)),
                ('answer_carb', models.BooleanField(default=False)),
                ('answer_fat', models.BooleanField(default=False)),
                ('answer_weight', models.BooleanField(default=False)),
            ],
        ),
    ]
