# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 07:46


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0050_admissiontest_admissiontestquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmissionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(b'NOT_STARTED', '\u041d\u0435 \u0434\u043e\u0448\u0435\u043b'), (b'IN_PROGRESS', '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (b'DONE', '\u0417\u0430\u0432\u0435\u0440\u0448\u0438\u043b'), (b'PASSED', '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e, \u0432\u0441\u0451 \u043e\u043a'), (b'FAILED', '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e, \u0437\u0430\u0432\u0430\u043b\u0438\u043b')], default=b'NOT_STARTED', max_length=100)),
                ('question_asked', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmissionTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.SmallIntegerField()),
                ('is_answered', models.BooleanField(default=False)),
                ('text', markdownx.models.MarkdownxField()),
                ('answer_ok', models.BooleanField(default=False)),
                ('answer_ok_comment', models.TextField(blank=True, null=True)),
                ('answer_sweet', models.BooleanField(default=False)),
                ('answer_sweet_comment', models.TextField(blank=True, null=True)),
                ('answer_interval', models.BooleanField(default=False)),
                ('answer_interval_comment', models.TextField(blank=True, null=True)),
                ('answer_protein', models.BooleanField(default=False)),
                ('answer_protein_comment', models.TextField(blank=True, null=True)),
                ('answer_carb', models.BooleanField(default=False)),
                ('answer_carb_comment', models.TextField(blank=True, null=True)),
                ('answer_fat', models.BooleanField(default=False)),
                ('answer_fat_comment', models.TextField(blank=True, null=True)),
                ('answer_weight', models.BooleanField(default=False)),
                ('answer_weight_comment', models.TextField(blank=True, null=True)),
                ('admission_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.UserAdmissionTest')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AdmissionTestQuestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='admissiontest',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdmissionTest',
        ),
    ]
