# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 08:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20180108_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_carb',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_fat',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0435\u0432\u044b\u0448\u0435\u043d\u0438\u0435 \u0436\u0438\u0440\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_interval',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430\u0440\u0443\u0448\u0435\u043d\u044b \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_ok',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043c\u0435\u0442\u043e\u0434\u0438\u0447\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_protein',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u043a \u0431\u0435\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_sweet',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043b\u0430\u0434\u043a\u043e\u0435 \u043d\u0430\u0442\u043e\u0449\u0430\u043a'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_weight',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0435 \u043d\u0430\u0432\u0435\u0441\u043a\u0438'),
        ),
    ]
