# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 10:40


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_auto_20180111_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradmissiontestquestion',
            options={'ordering': ['admission_test', 'question_num']},
        ),
        migrations.AddField(
            model_name='useradmissiontest',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradmissiontest',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradmissiontest',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='useradmissiontest',
            index=models.Index(fields=['user'], name='content_use_user_id_6f3f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontest',
            index=models.Index(fields=['status'], name='content_use_status_11e166_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontestquestion',
            index=models.Index(fields=['is_answered'], name='content_use_is_answ_2bb87f_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontestquestion',
            index=models.Index(fields=['admission_test'], name='content_use_admissi_6e1d11_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontestquestion',
            index=models.Index(fields=['source_question'], name='content_use_source__e421eb_idx'),
        ),
    ]
