# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 10:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20180113_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='is_markdown',
            field=models.BooleanField(default=True),
        ),
    ]
