# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 19:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_dialogue_is_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='message_type',
            field=models.CharField(choices=[(b'QUESTION', '\u0412\u043e\u043f\u0440\u043e\u0441'), (b'FEEDBACK', '\u041e\u0442\u0437\u044b\u0432'), (b'MEAL', '\u0420\u0430\u0446\u0438\u043e\u043d'), (b'FORMULA', '\u0424\u043e\u0440\u043c\u0443\u043b\u0430')], max_length=100),
        ),
    ]
