# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-19 09:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_auto_20180121_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquestion',
            name='category',
            field=models.CharField(choices=[(b'GENERAL', '#\u0432\u043e\u043f\u0440\u043e\u0441'), (b'IG', '#\u0441\u043c\u0435\u043d\u0430\u043d\u0438\u043a\u0430'), (b'MEETING', '#\u0432\u043e\u043f\u0440\u043e\u0441\u044b\u043a\u043c\u0438\u0442\u0438\u043d\u0433\u0443'), (b'FEEDBACK', '#\u043e\u0442\u0437\u044b\u0432'), (b'MEAL', '#\u0440\u0430\u0446\u0438\u043e\u043d'), (b'DOC', '#\u0434\u043e\u043a')], max_length=50),
        ),
    ]
