# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 13:23


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0058_auto_20180219_1237'),
    ]

    database_operations = [
        migrations.AlterModelTable('AdmissionTestQuestion', 'crm_admissiontestquestion'),
        migrations.AlterModelTable('UserAdmissionTest', 'crm_useradmissiontest'),
        migrations.AlterModelTable('UserAdmissionTestQuestion', 'crm_useradmissiontestquestion'),
    ]

    state_operations = [
        migrations.DeleteModel('AdmissionTestQuestion'),
        migrations.DeleteModel('UserAdmissionTest'),
        migrations.DeleteModel('UserAdmissionTestQuestion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
