# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 19:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_auto_20180318_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u0441\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '\u0441\u0442\u0430\u0442\u044c\u0438'},
        ),
        migrations.AlterModelOptions(
            name='basics',
            options={'verbose_name': '\u0430\u0437\u044b', 'verbose_name_plural': '\u0430\u0437\u044b'},
        ),
        migrations.AlterModelOptions(
            name='chatquestion',
            options={'verbose_name': '\u0432\u043e\u043f\u0440\u043e\u0441 \u0432 \u0447\u0430\u0442\u0435', 'verbose_name_plural': '\u0432\u043e\u043f\u0440\u043e\u0441\u044b \u0432 \u0447\u0430\u0442\u0430\u0445'},
        ),
        migrations.AlterModelOptions(
            name='dialogue',
            options={'verbose_name': '\u0434\u0438\u0430\u043b\u043e\u0433', 'verbose_name_plural': '\u0434\u0438\u0430\u043b\u043e\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '\u0437\u0430\u043f\u0438\u0441\u044c \u043c\u0438\u0442\u0438\u043d\u0433\u0430', 'verbose_name_plural': '\u0437\u0430\u043f\u0438\u0441\u0438 \u043c\u0438\u0442\u0438\u043d\u0433\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': '\u0440\u0435\u0446\u0435\u043f\u0442', 'verbose_name_plural': '\u0440\u0435\u0446\u0435\u043f\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='tgchat',
            options={'verbose_name': '\u0447\u0430\u0442 Telegram', 'verbose_name_plural': '\u0447\u0430\u0442\u044b Telegram'},
        ),
        migrations.AlterModelOptions(
            name='tgchatparticipant',
            options={'verbose_name': '\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a \u0447\u0430\u0442\u0430', 'verbose_name_plural': '\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438 \u0447\u0430\u0442\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='tgmessage',
            options={'verbose_name': '\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u0447\u0430\u0442\u0431\u043e\u0442\u0443', 'verbose_name_plural': '\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f \u0447\u0430\u0442\u0431\u043e\u0442\u0443'},
        ),
        migrations.AlterModelOptions(
            name='tgpost',
            options={'verbose_name': '\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u0432 \u043a\u0430\u043d\u0430\u043b\u0435', 'verbose_name_plural': '\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f \u0432 \u043a\u0430\u043d\u0430\u043b\u0435'},
        ),
        migrations.AddIndex(
            model_name='tgchatparticipant',
            index=models.Index(fields=['status'], name='content_tgc_status_5f7026_idx'),
        ),
        migrations.AddIndex(
            model_name='tgchatparticipant',
            index=models.Index(fields=['user'], name='content_tgc_user_id_2b0a23_idx'),
        ),
        migrations.AddIndex(
            model_name='tgchatparticipant',
            index=models.Index(fields=['chat'], name='content_tgc_chat_id_44b118_idx'),
        ),
    ]
