# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 22:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_auto_20180318_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[(b'REGULAR', '\u0411\u043e\u043b\u044c\u0448\u043e\u0439 \u043c\u0438\u0442\u0438\u043d\u0433'), (b'NEWBY', '\u041d\u043e\u0432\u0438\u0447\u043a\u043e\u0432\u044b\u0439 \u043c\u0438\u0442\u0438\u043d\u0433')], default=b'REGULAR', max_length=100),
        ),
    ]
