# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-02 11:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_auto_20180330_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_video',
            field=models.BooleanField(default=False, verbose_name='\u0415\u0441\u0442\u044c \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
