# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-18 11:09


from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_article_has_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', markdownx.models.MarkdownxField()),
                ('is_visible', models.BooleanField(default=True)),
                ('display_mode', models.CharField(choices=[(b'default', b'Default'), (b'success', b'Success'), (b'info', b'Info'), (b'primary', b'Primary'), (b'warning', b'Warning'), (b'danger', b'Danger')], default=b'default', max_length=50)),
                ('order_num', models.IntegerField(blank=True, default=99)),
            ],
            options={
                'ordering': ['order_num'],
                'verbose_name': '\u0448\u0430\u0431\u043b\u043e\u043d \u0430\u043d\u0430\u043b\u0438\u0437\u0430',
                'verbose_name_plural': '\u0448\u0430\u0431\u043b\u043e\u043d\u044b \u0430\u043d\u0430\u043b\u0438\u0437\u0430',
            },
        ),
    ]
