# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-14 16:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_analysistemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[(b'PENDING', b'Pending'), (b'UPLOADED', b'Uploaded'), (b'PROCESSING', b'Processing'), (b'READY', b'Ready for publication'), (b'PUBLISHED', b'Published'), (b'ERROR', b'Error')], default=b'PENDING', max_length=50),
        ),
    ]
