# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-26 22:03


from uuid import uuid4

from django.db import migrations, models

import content.models


def set_my_defaults(apps, schema_editor):
    Article = apps.get_model('content', 'Article')

    for article in Article.objects.filter(uid__isnull=True).only('id').iterator():
        # на всякий случай проверим
        article.uid = str(uuid4().hex)
        article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.picture_upload_to),
        ),

        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.CharField(blank=True, default=content.models.generate_uuid, max_length=32),
        ),

        migrations.RunPython(set_my_defaults, reverse_code=migrations.RunPython.noop),
    ]
