# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-07 05:26


import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_article_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.picture_upload_to, verbose_name='\u0417\u0430\u0433\u043b\u0430\u0432\u043d\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
