# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-02 05:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_auto_20180907_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='delay_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
