# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-02 05:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_auto_20181102_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='delay_days',
            field=models.IntegerField(blank=True, default=56),
        ),
    ]
