# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-21 03:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_auto_20181102_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistemplate',
            name='add_fat',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_calories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_carb_bread_late',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_carb_bread_min',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_carb_carb_vegs',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_fruits',
            field=models.CharField(blank=True, choices=[(b'NO', '\u0431\u0435\u0437 \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u0439'), (b'RESTRICT', '\u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u0435 \u0444\u0440\u0443\u043a\u0442\u043e\u0432'), (b'EXCLUDE', '\u0437\u0430\u043c\u0435\u043d\u0430 \u0444\u0440\u0443\u043a\u0442\u043e\u0432')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_protein',
            field=models.BooleanField(default=False),
        ),
    ]
