# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-01 22:50


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0070_auto_20181221_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[(b'PENDING', 'Pending'), (b'SENT', 'Sent'), (b'ERROR', 'Error')], default=b'PENDING', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default=b'', null=True)),
                ('sent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.TGMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TGNotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('display_mode', models.CharField(choices=[(b'default', b'Default'), (b'success', b'Success'), (b'info', b'Info'), (b'primary', b'Primary'), (b'warning', b'Warning'), (b'danger', b'Danger')], default=b'default', max_length=50)),
                ('order_num', models.IntegerField(blank=True, default=99)),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.AddIndex(
            model_name='tgnotification',
            index=models.Index(fields=['status'], name='content_tgn_status_181e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='tgnotification',
            index=models.Index(fields=['user'], name='content_tgn_user_id_e5415e_idx'),
        ),
        migrations.AddIndex(
            model_name='tgnotification',
            index=models.Index(fields=['fingerprint'], name='content_tgn_fingerp_0d3f74_idx'),
        ),
    ]
