# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-21 13:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_auto_20190202_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='status',
            field=models.CharField(choices=[(b'NEW', '\u041d\u043e\u0432\u044b\u0439'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0451\u043d'), (b'CANCELED', '\u041e\u0442\u043c\u0435\u043d\u0451\u043d'), (b'ANSWERED', '\u041e\u0442\u0432\u0435\u0447\u0435\u043d'), (b'POSTPONED', '\u041e\u0442\u043b\u043e\u0436\u0435\u043d')], default=b'NEW', max_length=20),
        ),
    ]
