# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-11 09:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20190321_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgnotificationtemplate',
            name='system_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
