# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-02 09:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_tgnotificationtemplate_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistemplate',
            name='system_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='analysistemplate',
            index=models.Index(fields=['is_visible'], name='content_ana_is_visi_74552c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistemplate',
            index=models.Index(fields=['order_num'], name='content_ana_order_n_d61eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistemplate',
            index=models.Index(fields=['system_code'], name='content_ana_system__62f13f_idx'),
        ),
    ]
