# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-13 18:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_auto_20191002_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_carb_sub_breakfast',
            field=models.NullBooleanField(),
        ),
    ]
