# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-13 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_analysistemplate_adjust_carb_sub_breakfast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uid',
        ),
    ]
