# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-22 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_analysistemplate_adjust_carb_sub_breakfast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_questions_replies_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatquestion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_questions_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='next_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.TGChat'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_to', to='content.TGPost'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgnotification',
            name='sent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.TGMessage'),
        ),
    ]
