# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-13 19:51
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def create_uuid(apps, schema_editor):
    Article = apps.get_model('content', 'Article')
    for a in Article.objects.all():
        a.uid = uuid.uuid4()
        a.save()


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0076_remove_article_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.UUIDField(blank=True, null=True),

        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='article',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
