# Generated by Django 2.2 on 2020-03-21 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_auto_20200122_0621'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tgpost',
            name='content_tgp_channel_27ba28_idx',
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_fruits',
            field=models.CharField(blank=True, choices=[('NO', 'без дополнительных ограничений'), ('RESTRICT', 'ограничение фруктов'), ('EXCLUDE', 'замена фруктов')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='display_mode',
            field=models.CharField(choices=[('default', 'Default'), ('success', 'Success'), ('info', 'Info'), ('primary', 'Primary'), ('warning', 'Warning'), ('danger', 'Danger')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='has_video',
            field=models.BooleanField(blank=True, default=False, verbose_name='Есть видео'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='basics',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текст'), ('IMAGE', 'Изображение')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_questions_replies_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatquestion',
            name='category',
            field=models.CharField(choices=[('GENERAL', '#вопрос'), ('IG', '#сменаника'), ('MEETING', '#вопросыкмитингу'), ('FEEDBACK', '#отзыв'), ('MEAL', '#рацион'), ('DOC', '#док')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatquestion',
            name='is_answered',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='answered_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='is_markdown',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_playable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_uploaded',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY', 'Ready for publication'), ('PUBLISHED', 'Published'), ('ERROR', 'Error')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('REGULAR', 'Большой митинг'), ('NEWBY', 'Новичковый митинг')], default='REGULAR', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingplayhistory',
            name='item',
            field=models.CharField(blank=True, default='playlist', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='chat_type',
            field=models.CharField(blank=True, choices=[('CHAT', 'Chat'), ('CHANNEL', 'Channel')], default='CHAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='is_main',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='tgchat',
            name='is_moderated',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='tgchatparticipant',
            name='status',
            field=models.CharField(blank=True, choices=[('ALLOWED', 'Allowed'), ('JOINED', 'Joined'), ('LEFT', 'Left'), ('RESTRICTED', 'Restricted'), ('UNRESTRICTED', 'Unrestricted'), ('BANNED', 'Banned')], default='ALLOWED', max_length=50),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'ChannelAdmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='message_type',
            field=models.CharField(choices=[('QUESTION', 'Вопрос'), ('FEEDBACK', 'Отзыв'), ('MEAL', 'Рацион'), ('FORMULA', 'Формула')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'ChannelAdmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('REJECTED', 'Отклонён'), ('CANCELED', 'Отменён'), ('ANSWERED', 'Отвечен'), ('POSTPONED', 'Отложен')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='tgnotification',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tgnotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='PENDING', max_length=64),
        ),
        migrations.AlterField(
            model_name='tgnotificationtemplate',
            name='display_mode',
            field=models.CharField(choices=[('default', 'Default'), ('success', 'Success'), ('info', 'Info'), ('primary', 'Primary'), ('warning', 'Warning'), ('danger', 'Danger')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='tgnotificationtemplate',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='tgpost',
            name='author',
            field=models.ForeignKey(limit_choices_to={'groups__name__startswith': 'ChannelAdmin'}, on_delete=django.db.models.deletion.CASCADE, related_name='posts_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tgpost',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tgpost',
            name='is_posted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tgpost',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
