# Generated by Django 2.2 on 2020-05-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0077_auto_20200321_1033'),
        ('content', '0077_article_uid'),
    ]

    operations = [
    ]
