from aenum import Constant

# ОБЯЗАТЕЛЬНО!
# при добавлении сюда константы - сразу добавить ее в бд в content_tgtranslation


class NodeNames(Constant):
    MAIN_MENU = 'MAIN_MENU'
    BACK_TO_MAIN_MENU = 'BACK_TO_MAIN_MENU'
    MAIN_MENU_ROUTER = 'MAIN_MENU_ROUTER'

    BACK_TO_MAIN_MENU_BY_TIMEOUT = 'BACK_TO_MAIN_MENU_BY_TIMEOUT'

    Q_BASE = 'Q_BASE'

    Q = 'Q'
    Q_ROUTER = 'Q_ROUTER'
    Q_TECH = 'Q_TECH'
    Q_TECH_ROUTER = 'Q_TECH_ROUTER'
    Q_TECH_YES = 'Q_TECH_YES'
    Q_TECH_NO = 'Q_TECH_NO'
    Q_TECH_NO_ROUTER = 'Q_TECH_NO_ROUTER'
    Q_TECH_NO_INPUT = 'Q_TECH_NO_INPUT'

    Q_PROD = 'Q_PROD'
    Q_PROD_ROUTER = 'Q_PROD_ROUTER'
    Q_PROD_YES = 'Q_PROD_YES'
    Q_PROD_NO = 'Q_PROD_NO'
    Q_PROD_NO_ROUTER = 'Q_PROD_NO_ROUTER'
    Q_PROD_NO_INPUT = 'Q_PROD_NO_INPUT'

    Q_DATA = 'Q_DATA'

    Q_ANLZDIET = 'Q_ANLZDIET'
    Q_ANLZDIET_ROUTER = 'Q_ANLZDIET_ROUTER'
    Q_ANLZDIET_INPUT = 'Q_ANLZDIET_INPUT'
    Q_ANLZDIET_INPUT_ROUTER = 'Q_ANLZDIET_INPUT_ROUTER'
    Q_ANLZDIET_QUESTION_INPUT = 'Q_ANLZDIET_QUESTION_INPUT'

    Q_THR = 'Q_THR'
    Q_THR_TRUE = 'Q_THR_TRUE'
    Q_THR_FALSE = 'Q_THR_FALSE'
    Q_THR_FALSE_ROUTER = 'Q_THR_FALSE_ROUTER'
    Q_THR_FALSE_INPUT = 'Q_THR_FALSE_INPUT'

    Q_HUN = 'Q_HUN'
    Q_HUN_ROUTER = 'Q_HUN_ROUTER'
    Q_HUN_INPUT = 'Q_HUN_INPUT'
    Q_HUN_INPUT_ROUTER = 'Q_HUN_INPUT_ROUTER'
    Q_HUN_QUESTION_INPUT = 'Q_HUN_QUESTION_INPUT'

    Q_LRGPORT = 'Q_LRGPORT'

    Q_ORGDIET = 'Q_ORGDIET'
    Q_ORGDIET_ROUTER = 'Q_ORGDIET_ROUTER'
    Q_ORGDIET_NOW = 'Q_ORGDIET_NOW'
    Q_ORGDIET_NOW_ROUTER = 'Q_ORGDIET_NOW_ROUTER'
    Q_ORGDIET_COND = 'Q_ORGDIET_COND'
    Q_ORGDIET_COND_ROUTER = 'Q_ORGDIET_COND_ROUTER'
    Q_ORGDIET_COND_QUESTION_INPUT = 'Q_ORGDIET_COND_QUESTION_INPUT'
    Q_ORGDIET_NOW_INPUT = 'Q_ORGDIET_NOW_INPUT'
    Q_ORGDIET_NOW_INPUT_ROUTER = 'Q_ORGDIET_NOW_INPUT_ROUTER'
    Q_ORGDIET_NOW_QUESTION_INPUT = 'Q_ORGDIET_NOW_QUESTION_INPUT'

    Q_REGIME = 'Q_REGIME'
    Q_REGIME_ROUTER = 'Q_REGIME_ROUTER'
    Q_REGIME_INPUT = 'Q_REGIME_INPUT'

    Q_RECOM = 'Q_RECOM'
    Q_RECOM_ROUTER = 'Q_RECOM_ROUTER'
    Q_RECOM_WHY = 'Q_RECOM_WHY'
    Q_RECOM_ANLZ = 'Q_RECOM_ANLZ'
    Q_RECOM_IMPL = 'Q_RECOM_IMPL'
    Q_RECOM_NOIMPL = 'Q_RECOM_NOIMPL'

    Q_NOTHING_FOUND = 'Q_NOTHING_FOUND'
    Q_NOTHING_FOUND_ROUTER = 'Q_NOTHING_FOUND_ROUTER'
    Q_NOTHING_FOUND_INPUT = 'Q_NOTHING_FOUND_INPUT'

    NODATA = 'NODATA'

    DOC = 'DOC'
    DOC_ROUTER = 'DOC_ROUTER'
    DOC_INPUT = 'DOC_INPUT'

    RENEW = 'RENEW'
    RENEW_ROUTER = 'RENEW_ROUTER'
    RENEW_CONT = 'RENEW_CONT'
    RENEW_CONT_ROUTER = 'RENEW_CONT_ROUTER'
    RENEW_STOP = 'RENEW_STOP'
    RENEW_STOP_ROUTER = 'RENEW_STOP_ROUTER'
    RENEW_CONT_INPUT = 'RENEW_CONT_INPUT'
    RENEW_STOP_INPUT = 'RENEW_STOP_INPUT'

    DIARY = 'DIARY'
    DIARY_ROUTER = 'DIARY_ROUTER'
    DIARY_PUBLIC = 'DIARY_PUBLIC'
    DIARY_PUBLIC_ROUTER = 'DIARY_PUBLIC_ROUTER'
    DIARY_NOTPUBLIC = 'DIARY_NOTPUBLIC'
    DIARY_NOTPUBLIC_ROUTER = 'DIARY_NOTPUBLIC_ROUTER'
    DIARY_PUBLIC_INPUT = 'DIARY_PUBLIC_INPUT'
    DIARY_NOTPUBLIC_INPUT = 'DIARY_NOTPUBLIC_INPUT'


class NodeTranslations(NodeNames):
    MAIN_MENU__TXT = 'MAIN_MENU__TXT'
    BACK_TO_MAIN_MENU__TXT = 'BACK_TO_MAIN_MENU__TXT'
    BACK_TO_MAIN_MENU_BY_TIMEOUT__TXT = 'BACK_TO_MAIN_MENU_BY_TIMEOUT__TXT'
    CHOOSE_CORRECT_NODE__TXT = 'CHOOSE_CORRECT_NODE__TXT'
    TEXT_INPUT_VALIDATION_FAILED__TXT = 'TEXT_INPUT_VALIDATION_FAILED__TXT'
    TEXT_INPUT_MIN_MAX_VALIDATION_FAILED__TXT = 'TEXT_INPUT_MIN_MAX_VALIDATION_FAILED__TXT'
    TEXT_INPUT_EMOJI_NOT_ALLOWED__TXT = 'TEXT_INPUT_EMOJI_NOT_ALLOWED__TXT'
    TEXT_INPUT_HASHTAG_NOT_ALLOWED__TXT = 'TEXT_INPUT_HASHTAG_NOT_ALLOWED__TXT'
    COMMUNICATION_MODE_VALIDATION_FAILED__TXT = 'COMMUNICATION_MODE_VALIDATION_FAILED__TXT'
    LIMIT_PER_DAY_VALIDATION_FAILED__TXT = 'LIMIT_PER_DAY_VALIDATION_FAILED__TXT'
    LIMIT_PER_DAY_WARNING__TXT = 'LIMIT_PER_DAY_WARNING__TXT'
    LIMIT_PER_DAY_LAST_MESSAGE__TXT = 'LIMIT_PER_DAY_LAST_MESSAGE__TXT'
    WORK_DAY_VALIDATION_FAILED__TXT = 'WORK_DAY_VALIDATION_FAILED__TXT'
    FLOOD_CONTROL_VALIDATION_FAILED__TXT = 'FLOOD_CONTROL_VALIDATION_FAILED__TXT'

    Q__TXT = 'Q__TXT'

    Q_TECH__TXT_1 = 'Q_TECH__TXT_1'
    Q_TECH__TXT_2 = 'Q_TECH__TXT_2'
    Q_TECH__TXT_NO_QUESTIONS_TARIFF = 'Q_TECH__TXT_NO_QUESTIONS_TARIFF'
    Q_TECH_YES__TXT = 'Q_TECH_YES__TXT'
    Q_TECH_NO__TXT = 'Q_TECH_NO__TXT'
    Q_TECH_NO__SAVE_OK = 'Q_TECH_NO__SAVE_OK'

    Q_PROD__TXT_1 = 'Q_PROD__TXT_1'
    Q_PROD__TXT_2 = 'Q_PROD__TXT_2'
    Q_PROD__TXT_NO_QUESTIONS_TARIFF = 'Q_PROD__TXT_NO_QUESTIONS_TARIFF'
    Q_PROD_YES__TXT = 'Q_PROD_YES__TXT'
    Q_PROD_NO__TXT = 'Q_PROD_NO__TXT'
    Q_PROD_NO__SAVE_OK = 'Q_PROD_NO__SAVE_OK'

    Q_DATA__TXT = 'Q_DATA__TXT'

    Q_ANLZDIET__TXT = 'Q_ANLZDIET__TXT'
    Q_ANLZDIET__SAVE_OK_1 = 'Q_ANLZDIET__SAVE_OK_1'
    Q_ANLZDIET__SAVE_OK_2 = 'Q_ANLZDIET__SAVE_OK_2'

    Q_THR__TXT1 = 'Q_THR__TXT1'
    Q_THR__TXT2 = 'Q_THR__TXT2'
    Q_THR__SAVE_OK = 'Q_THR__SAVE_OK'

    Q_HUN__TXT = 'Q_HUN__TXT'
    Q_HUN__SAVE_OK_1 = 'Q_HUN__SAVE_OK_1'
    Q_HUN__SAVE_OK_2 = 'Q_HUN__SAVE_OK_2'

    Q_LRGPORT__TXT = 'Q_LRGPORT__TXT'

    Q_ORGDIET__TXT = 'Q_ORGDIET__TXT'
    Q_ORGDIET_NOW__TXT1 = 'Q_ORGDIET_NOW__TXT1'
    Q_ORGDIET_NOW__TXT2 = 'Q_ORGDIET_NOW__TXT2'
    Q_ORGDIET_COND__TXT = 'Q_ORGDIET_COND__TXT'
    Q_ORGDIET__SAVE_OK = 'Q_ORGDIET__SAVE_OK'

    Q_REGIME__TXT = 'Q_REGIME__TXT'
    Q_REGIME__SAVE_OK = 'Q_REGIME__SAVE_OK'

    Q_RECOM__TXT = 'Q_RECOM__TXT'
    Q_RECOM_ANLZ__TXT = 'Q_RECOM_ANLZ__TXT'
    Q_RECOM_WHY__TXT = 'Q_RECOM_WHY__TXT'
    Q_RECOM_IMPL__TXT = 'Q_RECOM_IMPL__TXT'
    Q_RECOM_NOIMPL__TXT = 'Q_RECOM_NOIMPL__TXT'

    Q_NOTHING_FOUND__TXT = 'Q_NOTHING_FOUND__TXT'
    Q_NOTHING_FOUND__SAVE_OK = 'Q_NOTHING_FOUND__SAVE_OK'

    NODATA__TXT = 'NODATA__TXT'

    DOC__TXT = 'DOC__TXT'
    DOC__SAVE_OK = 'DOC__SAVE_OK'

    RENEW__TXT = 'RENEW__TXT'
    RENEW_CONT__TXT = 'RENEW_CONT__TXT'
    RENEW_CONT__SAVE_OK = 'RENEW_CONT__SAVE_OK'
    RENEW_STOP__TXT = 'RENEW_STOP__TXT'
    RENEW_STOP__SAVE_OK = 'RENEW_STOP__SAVE_OK'

    DIARY__TXT = 'DIARY__TXT'
    DIARY_PUBLIC__TXT = 'DIARY_PUBLIC__TXT'
    DIARY_PUBLIC__SAVE_OK = 'DIARY_PUBLIC__SAVE_OK'
    DIARY_NOTPUBLIC__TXT = 'DIARY_NOTPUBLIC__TXT'
    DIARY_NOTPUBLIC__SAVE_OK = 'DIARY_NOTPUBLIC__SAVE_OK'

    GO_TO__CMD__START = 'GO_TO__CMD__START'
    CMD__START__TXT__ALREADY_ACTIVE = 'CMD__START__TXT__ALREADY_ACTIVE'
    CMD__START__TXT__ALREADY_BLOCKED = 'CMD__START__TXT__ALREADY_BLOCKED'
    CMD__START__TXT__SEND_CONTACT_BTN = 'CMD__START__TXT__SEND_CONTACT_BTN'
    CMD__START__TXT__REGISTRATION_PHONE_IS_REQUIRED = 'CMD__START__TXT__REGISTRATION_PHONE_IS_REQUIRED'

    CONTACT__TXT__ALREADY_ACTIVE = 'CONTACT__TXT__ALREADY_ACTIVE'
    CONTACT__TXT__CONFIRMATION_WRONG_USER = 'CONTACT__TXT__CONFIRMATION_WRONG_USER'
    CONTACT__TXT__CONFIRMATION_UNKNOWN_PHONE_NUMBER = 'CONTACT__TXT__CONFIRMATION_UNKNOWN_PHONE_NUMBER'
    CONTACT__TXT__SUCCESS = 'CONTACT__TXT__SUCCESS'
    CONTACT__TXT__SUCCESS__CHANNEL = 'CONTACT__TXT__SUCCESS__CHANNEL'

    FORMER_CLIENT__IS_IN_CLUB = 'FORMER_CLIENT__IS_IN_CLUB'
    FORMER_CLIENT__IS_NOT_IN_CLUB = 'FORMER_CLIENT__IS_NOT_IN_CLUB'

    FUTURE_CLIENT__NO_CAMPAIGN = 'FUTURE_CLIENT__NO_CAMPAIGN'

    FUTURE_CLIENT__CAMPAIGN__CHANNEL__NOT_FINISHED_TEST = 'FUTURE_CLIENT__CAMPAIGN__CHANNEL__NOT_FINISHED_TEST'
    FUTURE_CLIENT__CAMPAIGN__CHANNEL__FINISHED_TEST = 'FUTURE_CLIENT__CAMPAIGN__CHANNEL__FINISHED_TEST'
    FUTURE_CLIENT__CAMPAIGN__CHANNEL__ACCEPTED_TEST = 'FUTURE_CLIENT__CAMPAIGN__CHANNEL__ACCEPTED_TEST'
    FUTURE_CLIENT__CAMPAIGN__CHANNEL__REJECTED_TEST = 'FUTURE_CLIENT__CAMPAIGN__CHANNEL__REJECTED_TEST'

    FUTURE_CLIENT__CAMPAIGN__NOT_CHANNEL = 'FUTURE_CLIENT__CAMPAIGN__NOT_CHANNEL'

    FUTURE_CLIENT__NOT_NEAREST__CHANNEL = 'FUTURE_CLIENT__NOT_NEAREST__CHANNEL'
    FUTURE_CLIENT__NOT_NEAREST__CHAT = 'FUTURE_CLIENT__NOT_NEAREST__CHAT'

    CLIENT__NO_WAVE = 'CLIENT__NO_WAVE'

    CAMPAIGN__NEAREST__UNDEFINED = 'CAMPAIGN__NEAREST__UNDEFINED'
