# Generated by Django 3.0.6 on 2020-05-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_squashed_0007_auto_20200321_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='signature',
            field=models.CharField(max_length=64),
        ),
    ]
