# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 12:41


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('mailchimp_group_id', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
