# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 18:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['start_date']},
        ),
    ]
