# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 20:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180120_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
