# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 09:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_campaign_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_admission_open',
            field=models.BooleanField(default=False),
        ),
    ]
