# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 15:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180223_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u0421\u0447\u0451\u0442', 'verbose_name_plural': '\u0421\u0447\u0435\u0442\u0430'},
        ),
    ]
