# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 13:30


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_auto_20180305_0936'),
        ('content', '0059_auto_20180318_1623'),
        ('srbc', '0142_auto_20180318_1623'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='AdmissionTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField()),
                ('is_active', models.BooleanField(default=False)),
                ('answer_ok', models.BooleanField(default=False, verbose_name='\u0421\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043c\u0435\u0442\u043e\u0434\u0438\u0447\u043a\u0435')),
                ('answer_sweet', models.BooleanField(default=False, verbose_name='\u0421\u043b\u0430\u0434\u043a\u043e\u0435 \u043d\u0430\u0442\u043e\u0449\u0430\u043a')),
                ('answer_interval', models.BooleanField(default=False, verbose_name='\u041d\u0430\u0440\u0443\u0448\u0435\u043d\u044b \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b\u044b')),
                ('answer_protein', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u043a \u0431\u0435\u043b\u043a\u0430')),
                ('answer_carb', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u043e\u0432')),
                ('answer_fat', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0435\u0432\u044b\u0448\u0435\u043d\u0438\u0435 \u0436\u0438\u0440\u043d\u043e\u0441\u0442\u0438')),
                ('answer_weight', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0435 \u043d\u0430\u0432\u0435\u0441\u043a\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'M', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), (b'F', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], default=b'F', max_length=1, verbose_name='\u041f\u043e\u043b')),
                ('is_payment_allowed', models.BooleanField(default=False, verbose_name='\u0420\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u0430 \u043e\u043f\u043b\u0430\u0442\u0430')),
                ('first_name', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=100, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('email', models.EmailField(max_length=254, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430')),
                ('email_status', models.CharField(blank=True, choices=[(b'NEW', '\u041d\u043e\u0432\u044b\u0439'), (b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f'), (b'APPROVED', '\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'), (b'DISCONNECTED', '\u041e\u0442\u043f\u0438\u0441\u0430\u043d')], default=b'NEW', max_length=25)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u0433\u043e \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('height', models.IntegerField(null=True, verbose_name='\u0412\u0430\u0448 \u0440\u043e\u0441\u0442')),
                ('weight', shared.models.DecimalRangeField(decimal_places=3, max_digits=8, null=True, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043a\u0443\u0449\u0438\u0439 (\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u044b\u0439) \u0432\u0435\u0441')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='\u0412\u0430\u0448 \u0432\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('birth_year', models.IntegerField(null=True, verbose_name='\u0413\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('sickness', models.TextField(null=True, verbose_name='\u0418\u043c\u0435\u044e\u0449\u0438\u0435\u0441\u044f \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u044f')),
                ('goals', models.TextField(null=True, verbose_name='\u0426\u0435\u043b\u0438 \u043d\u0430 \u043c\u0430\u0440\u0430\u0444\u043e\u043d')),
                ('need_tracker', models.BooleanField(default=False, verbose_name='\u0425\u043e\u0447\u0443 \u0444\u0438\u0442\u043d\u0435\u0441\u0441-\u0442\u0440\u0435\u043a\u0435\u0440')),
                ('is_approved', models.BooleanField(default=False, verbose_name='\u0410\u043d\u043a\u0435\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u0430')),
                ('social_acc_status', models.CharField(blank=True, choices=[(b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f'), (b'APPROVED', '\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'), (b'SUSPICIOUS', '\u041f\u043e\u0434\u043e\u0437\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0451\u043d')], default=b'PENDING', max_length=25)),
                ('admission_status', models.CharField(blank=True, choices=[(b'NOT_STARTED', '\u041d\u0435 \u0434\u043e\u0448\u0435\u043b'), (b'IN_PROGRESS', '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (b'DONE', '\u0417\u0430\u0432\u0435\u0440\u0448\u0438\u043b'), (b'PASSED', '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e, \u0432\u0441\u0451 \u043e\u043a'), (b'FAILED', '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e, \u0437\u0430\u0432\u0430\u043b\u0438\u043b'), (b'REJECTED', '\u041e\u0442\u043a\u0430\u0437\u0430\u043d\u043e'), (b'ACCEPTED', '\u041f\u0440\u0438\u043d\u044f\u0442')], default=b'NOT_STARTED', max_length=100)),
                ('tos_signed_date', models.DateTimeField(blank=True, null=True)),
                ('active_payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Order')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Campaign')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmissionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(b'NOT_STARTED', '\u041d\u0435 \u0434\u043e\u0448\u0435\u043b'), (b'IN_PROGRESS', '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (b'DONE', '\u0417\u0430\u0432\u0435\u0440\u0448\u0438\u043b'), (b'PASSED', '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e, \u0432\u0441\u0451 \u043e\u043a'), (b'FAILED', '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e, \u0437\u0430\u0432\u0430\u043b\u0438\u043b'), (b'REJECTED', '\u041e\u0442\u043a\u0430\u0437\u0430\u043d\u043e'), (b'ACCEPTED', '\u041f\u0440\u0438\u043d\u044f\u0442')], default=b'NOT_STARTED', max_length=100)),
                ('question_asked', models.TextField(blank=True, null=True)),
                ('recommendation_info', models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0440\u0435\u043a\u043e\u043c\u043c\u0435\u043d\u0434\u0430\u0442\u0435\u043b\u0435')),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmissionTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.SmallIntegerField()),
                ('is_answered', models.BooleanField(default=False)),
                ('text', markdownx.models.MarkdownxField()),
                ('answer_ok', models.BooleanField(default=False, verbose_name='\u0421\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043c\u0435\u0442\u043e\u0434\u0438\u0447\u043a\u0435')),
                ('answer_ok_comment', models.TextField(blank=True, null=True)),
                ('answer_sweet', models.BooleanField(default=False, verbose_name='\u0421\u043b\u0430\u0434\u043a\u043e\u0435 \u043d\u0430\u0442\u043e\u0449\u0430\u043a')),
                ('answer_sweet_comment', models.TextField(blank=True, null=True)),
                ('answer_interval', models.BooleanField(default=False, verbose_name='\u041d\u0430\u0440\u0443\u0448\u0435\u043d\u044b \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b\u044b')),
                ('answer_interval_comment', models.TextField(blank=True, null=True)),
                ('answer_protein', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u043a \u0431\u0435\u043b\u043a\u0430')),
                ('answer_protein_comment', models.TextField(blank=True, null=True)),
                ('answer_carb', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u043e\u0432')),
                ('answer_carb_comment', models.TextField(blank=True, null=True)),
                ('answer_fat', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0435\u0432\u044b\u0448\u0435\u043d\u0438\u0435 \u0436\u0438\u0440\u043d\u043e\u0441\u0442\u0438')),
                ('answer_fat_comment', models.TextField(blank=True, null=True)),
                ('answer_weight', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0435 \u043d\u0430\u0432\u0435\u0441\u043a\u0438')),
                ('answer_weight_comment', models.TextField(blank=True, null=True)),
                ('admission_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='crm.UserAdmissionTest')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_usage', to='crm.AdmissionTestQuestion')),
            ],
            options={
                'ordering': ['admission_test', 'question_num'],
            },
        ),
        migrations.AddIndex(
            model_name='useradmissiontestquestion',
            index=models.Index(fields=['is_answered'], name='crm_useradm_is_answ_6808ea_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontestquestion',
            index=models.Index(fields=['admission_test'], name='crm_useradm_admissi_9191b1_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontestquestion',
            index=models.Index(fields=['source_question'], name='crm_useradm_source__dac47c_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontest',
            index=models.Index(fields=['user'], name='crm_useradm_user_id_63b73c_idx'),
        ),
        migrations.AddIndex(
            model_name='useradmissiontest',
            index=models.Index(fields=['status'], name='crm_useradm_status_11a323_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='crm_applica_user_id_6b1984_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['need_tracker'], name='crm_applica_need_tr_9fc937_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_approved'], name='crm_applica_is_appr_1fc7e9_idx'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
