# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-25 16:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20180318_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_payment_special',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0441\u043e\u0431\u044b\u0435 \u0443\u0441\u043b\u043e\u0432\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
