# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 22:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_application_is_payment_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='goals',
            field=models.TextField(null=True, verbose_name='\u0426\u0435\u043b\u0438 \u043d\u0430 \u043f\u0440\u043e\u0435\u043a\u0442\u0435'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='payment_type',
            field=models.CharField(blank=True, choices=[(b'CLUB', '\u041e\u043f\u043b\u0430\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043a\u043b\u0443\u0431\u0435'), (b'CHANNEL', '\u041e\u043f\u043b\u0430\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043f\u0440\u043e\u0435\u043a\u0442\u0435 (\u0437\u0430\u043e\u0447\u043d\u044b\u0439)'), (b'CHAT', '\u041e\u043f\u043b\u0430\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043f\u0440\u043e\u0435\u043a\u0442\u0435 (\u043e\u0447\u043d\u044b\u0439)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[(b'CLUB', '\u041e\u043f\u043b\u0430\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043a\u043b\u0443\u0431\u0435'), (b'CHANNEL', '\u041e\u043f\u043b\u0430\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043f\u0440\u043e\u0435\u043a\u0442\u0435 (\u0437\u0430\u043e\u0447\u043d\u044b\u0439)'), (b'CHAT', '\u041e\u043f\u043b\u0430\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043f\u0440\u043e\u0435\u043a\u0442\u0435 (\u043e\u0447\u043d\u044b\u0439)')], max_length=100),
        ),
    ]
