# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 06:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_renewalrequest_payment_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequest',
            name='comment_internal',
            field=models.TextField(blank=True, default=b'', verbose_name='\u0421\u043b\u0443\u0436\u0435\u0431\u043d\u0430\u044f \u0437\u0430\u043c\u0435\u0442\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='status',
            field=models.CharField(blank=True, choices=[(b'NEW', '\u041d\u043e\u0432\u044b\u0439'), (b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043e\u0442\u0432\u0435\u0442\u0430 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430'), (b'PREACCEPTED', '\u041f\u0440\u0435\u0434\u0432\u0430\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u043e\u0434\u043e\u0431\u0440\u0435\u043d'), (b'TBD', '\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u0438\u0435'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d'), (b'ACCEPTED', '\u041e\u0434\u043e\u0431\u0440\u0435\u043d')], default=b'NEW', max_length=25),
        ),
    ]
