# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 09:19


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0019_auto_20180404_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operation', models.CharField(choices=[(b'TOPUP', '\u041f\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435'), (b'TARIFF_SETUP', '\u0421\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e \u0442\u0430\u0440\u0438\u0444\u0443 - \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u0447\u043d\u043e\u0435'), (b'TARIFF_REGULAR', '\u0421\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e \u0442\u0430\u0440\u0438\u0444\u0443 - \u0440\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u043e\u0435'), (b'EXTRA', '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0443\u0441\u043b\u0443\u0433\u0438'), (b'REFUND', '\u0412\u043e\u0437\u0432\u0440\u0430\u0442 \u0441\u0440\u0435\u0434\u0441\u0442\u0432')], max_length=25)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'ACTIVE', '\u0414\u0435\u0439\u0441\u0442\u0432\u0443\u044e\u0449\u0430\u044f'), (b'CANCELLED', '\u041e\u0442\u043c\u0435\u043d\u0435\u043d\u043d\u0430\u044f'), (b'PENDING', '\u041f\u0440\u0435\u0434\u0441\u0442\u043e\u044f\u0449\u0430\u044f')], default=b'ACTIVE', max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('setup_fee_rub', models.DecimalField(decimal_places=2, max_digits=7)),
                ('periodic_price_rub', models.DecimalField(decimal_places=2, max_digits=7)),
                ('setup_fee_eur', models.DecimalField(decimal_places=2, max_digits=7)),
                ('periodic_price_eur', models.DecimalField(decimal_places=2, max_digits=7)),
                ('billing_interval', models.CharField(choices=[(b'DAY', '\u0414\u0435\u043d\u044c'), (b'MONTH', '\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u043d\u044b\u0439 \u043c\u0435\u0441\u044f\u0446')], max_length=20)),
                ('duration', models.IntegerField()),
                ('next_tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Tariff')),
            ],
        ),
    ]
