# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 15:29


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0161_auto_20180408_1213'),
        ('crm', '0020_billingtransaction_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequest',
            name='usernote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.UserNote'),
        ),
    ]
