# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 10:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_renewalrequest_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
