# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-30 13:14


from django.db import migrations, models
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20180419_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='height',
            field=models.IntegerField(null=True, verbose_name='\u0412\u0430\u0448 \u0440\u043e\u0441\u0442, \u0432 \u0441\u043c'),
        ),
        migrations.AlterField(
            model_name='application',
            name='weight',
            field=shared.models.DecimalRangeField(decimal_places=3, max_digits=8, null=True, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043a\u0443\u0449\u0438\u0439 (\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u044b\u0439) \u0432\u0435\u0441, \u0432 \u043a\u0433'),
        ),
    ]
