# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 12:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20180430_1614'),
        ('crm', '0023_auto_20180502_1430'),
    ]

    operations = [
    ]
