# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 15:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_merge_20180516_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wave_to_join', to='srbc.Wave', verbose_name='Payment wave'),
        ),
    ]
