# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 09:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20180730_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='next_tariff',
        ),
        migrations.DeleteModel(
            name='BillingTransaction',
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
