# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-27 18:16


from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20180921_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('text', markdownx.models.MarkdownxField(blank=True, default=b'', null=True)),
            ],
        ),
    ]
