# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-19 09:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_telegrammailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='country',
            new_name='country_old',
        ),
    ]
