# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-19 09:28


from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20190119_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=django_countries.fields.CountryField(default='RU', max_length=2),
            preserve_default=False,
        ),
    ]
