# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-19 09:45


from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_application_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
    ]
