# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-20 17:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20190119_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_admission_open',
        ),
    ]
