# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-05 11:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0247_auto_20190805_1433'),
        ('crm', '0035_auto_20190121_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.Tariff'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_provider'], name='crm_order_payment_94f232_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_type'], name='crm_order_payment_0afeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['currency'], name='crm_order_currenc_6b9068_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='crm_order_status_51dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_id'], name='crm_order_payment_699f3d_idx'),
        ),
    ]
