# Generated by Django 2.2 on 2020-03-21 07:33

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20200122_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_carb',
            field=models.BooleanField(blank=True, default=False, verbose_name='Неверное количество углеводов'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_fat',
            field=models.BooleanField(blank=True, default=False, verbose_name='Превышение жирности'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_interval',
            field=models.BooleanField(blank=True, default=False, verbose_name='Нарушены интервалы'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_ok',
            field=models.BooleanField(blank=True, default=False, verbose_name='Соответствует методичке'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_protein',
            field=models.BooleanField(blank=True, default=False, verbose_name='Недостаток белка'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_sweet',
            field=models.BooleanField(blank=True, default=False, verbose_name='Сладкое натощак'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='answer_weight',
            field=models.BooleanField(blank=True, default=False, verbose_name='Неверные навески'),
        ),
        migrations.AlterField(
            model_name='admissiontestquestion',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Не дошел'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Завершил'), ('PASSED', 'Проверено, всё ок'), ('FAILED', 'Проверено, завалил'), ('REJECTED', 'Отказано'), ('ACCEPTED', 'Принят')], default='NOT_STARTED', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='baby_case',
            field=models.CharField(choices=[('PREGNANT', 'Беременность'), ('FEEDING', 'Кормление грудью'), ('NONE', 'Ничего из перечисленного')], default='NONE', max_length=100, verbose_name='Особый случай'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email_status',
            field=models.CharField(blank=True, choices=[('NEW', 'Новый'), ('PENDING', 'Ожидает подтверждения'), ('APPROVED', 'Подтвержден'), ('DISCONNECTED', 'Отписан')], default='NEW', max_length=25),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='F', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Анкета проверена'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_payment_allowed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Разрешена оплата'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_payment_special',
            field=models.BooleanField(blank=True, default=False, verbose_name='Особые условия оплаты'),
        ),
        migrations.AlterField(
            model_name='application',
            name='need_tracker',
            field=models.BooleanField(blank=True, default=False, verbose_name='Хочу фитнесс-трекер'),
        ),
        migrations.AlterField(
            model_name='application',
            name='social_acc_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Ожидает подтверждения'), ('APPROVED', 'Подтвержден'), ('SUSPICIOUS', 'Подозрительный'), ('REJECTED', 'Отклонён')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_applied',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CLUB', 'Оплата участия в клубе'), ('CHANNEL', 'Оплата участия в проекте (заочный)'), ('CHAT', 'Оплата участия в проекте (очный)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('EUR', 'Евро')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('YA', 'Яндекс-Касса'), ('PP', 'PayPal'), ('MANUAL', 'Вручную')], default='YA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CLUB', 'Оплата участия в клубе'), ('CHANNEL', 'Оплата участия в проекте (заочный)'), ('CHAT', 'Оплата участия в проекте (очный)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PROCESSING', 'В обработке'), ('APPROVED', 'Оплачен'), ('CANCELED', 'Отменен')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='comment_internal',
            field=models.TextField(blank=True, default='', verbose_name='Служебная заметка'),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='payment_special',
            field=models.BooleanField(blank=True, default=False, verbose_name='Особые условия оплаты'),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='request_type',
            field=models.CharField(choices=[('POSITIVE', '#япродолжаю'), ('NEGATIVE', '#яНЕпродолжаю')], max_length=10, verbose_name='Хэштег'),
        ),
        migrations.AlterField(
            model_name='renewalrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'Новый'), ('PENDING', 'Ожидает ответа участника'), ('PREACCEPTED', 'Предварительно одобрен'), ('TBD', 'Требуется согласование'), ('REJECTED', 'Отклонен'), ('ACCEPTED', 'Одобрен')], default='NEW', max_length=25),
        ),
        migrations.AlterField(
            model_name='telegrammailtemplate',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useradmissiontest',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'Не дошел'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Завершил'), ('PASSED', 'Проверено, всё ок'), ('FAILED', 'Проверено, завалил'), ('REJECTED', 'Отказано'), ('ACCEPTED', 'Принят')], default='NOT_STARTED', max_length=100),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_carb',
            field=models.BooleanField(blank=True, default=False, verbose_name='Неверное количество углеводов'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_fat',
            field=models.BooleanField(blank=True, default=False, verbose_name='Превышение жирности'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_interval',
            field=models.BooleanField(blank=True, default=False, verbose_name='Нарушены интервалы'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_ok',
            field=models.BooleanField(blank=True, default=False, verbose_name='Соответствует методичке'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_protein',
            field=models.BooleanField(blank=True, default=False, verbose_name='Недостаток белка'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_sweet',
            field=models.BooleanField(blank=True, default=False, verbose_name='Сладкое натощак'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='answer_weight',
            field=models.BooleanField(blank=True, default=False, verbose_name='Неверные навески'),
        ),
        migrations.AlterField(
            model_name='useradmissiontestquestion',
            name='is_answered',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
