# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[(b'NEW', '\u041d\u043e\u0432\u044b\u0439'), (b'ASSIGNED', '\u0412 \u0440\u0430\u0431\u043e\u0442\u0435'), (b'RESOLVED', '\u041e\u0442\u0432\u0435\u0447\u0435\u043d'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d')], default=b'NEW', max_length=20),
        ),
    ]
