# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170715_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='signature',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
