# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticket_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.TextField(max_length=100),
        ),
    ]
