# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20170715_2246'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['signature'], name='support_tic_signatu_80b690_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['posted_at'], name='support_tic_posted__54b954_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee'], name='support_tic_assigne_d963a3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='support_tic_status_363e60_idx'),
        ),
    ]
