# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 22:19


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('front_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('side_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rear_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('measurements_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('trueweight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('meals', models.SmallIntegerField(blank=True, null=True)),
                ('faults', models.SmallIntegerField(blank=True, null=True)),
                ('meal_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'M', 'Male'), (b'F', 'Female')], default=b'F', max_length=1)),
                ('instagram', models.CharField(max_length=100)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('sugar_status', models.IntegerField(choices=[(0, 'Normal'), (1, 'IR'), (2, 'GT'), (3, 'Diabetic'), (99, 'Unknown')], default=0)),
                ('treatment', models.TextField(blank=True, default=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=b'')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
