# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0039_auto_20170621_1931'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='diaryrecord',
            index_together=set([]),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['user'], name='srbc_userno_user_id_33d6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['label'], name='srbc_userno_label_9e23e8_idx'),
        ),
        migrations.AddIndex(
            model_name='userbookmark',
            index=models.Index(fields=['user'], name='srbc_userbo_user_id_dd76d4_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='srbc_profil_user_id_33391d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['wave'], name='srbc_profil_wave_id_bccb65_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['group_leader'], name='srbc_profil_group_l_6277ea_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active'], name='srbc_profil_is_acti_839080_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_in_club'], name='srbc_profil_is_in_c_1eeaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['data_sergeant'], name='srbc_profil_data_se_611c12_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['meals_sergeant'], name='srbc_profil_meals_s_15fc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryrecord',
            index=models.Index(fields=['user', 'date'], name='srbc_diaryr_user_id_18de8d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='srbc_applic_user_id_295313_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['need_tracker'], name='srbc_applic_need_tr_3d5d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_approved'], name='srbc_applic_is_appr_4b1c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_tracker_payment_received'], name='srbc_applic_is_trac_f0fd65_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_tracker_sent'], name='srbc_applic_is_trac_0b5fca_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_tracker_received'], name='srbc_applic_is_trac_262a72_idx'),
        ),
    ]
