# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:38


from django.db import migrations
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0040_auto_20170622_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='weight',
            field=srbc.models.DecimalRangeField(decimal_places=3, default=0, max_digits=8, verbose_name='\u0412\u0430\u0448 \u0442\u0435\u043a\u0443\u0449\u0438\u0439 (\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u044b\u0439) \u0432\u0435\u0441'),
            preserve_default=False,
        ),
    ]
