# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0042_profile_is_instagram_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
