# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0045_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_perfect_weight',
            field=models.BooleanField(default=False),
        ),
    ]
