# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:25


import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0046_profile_is_perfect_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('meal_type', models.CharField(choices=[(b'PREBREAKFAST', '\u041f\u0440\u0435\u0434\u0437\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BREAKFAST', '\u0417\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BRUNCH', '\u0412\u0417'), (b'LUNCH', '\u041e\u0431\u0435\u0434'), (b'MERIENDA', '\u041f\u043e\u043b\u0434\u043d\u0438\u043a'), (b'DINNER', '\u0423\u0436\u0438\u043d'), (b'SNACK', '\u041f\u0435\u0440\u0435\u043a\u0443\u0441')], max_length=25)),
                ('is_sweet', models.BooleanField(default=False)),
                ('is_filled', models.BooleanField(default=False)),
                ('is_overcalory', models.BooleanField(default=False)),
                ('scores', srbc.models.IntegerRangeField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('amount', srbc.models.DecimalRangeField(decimal_places=3, max_digits=8, verbose_name='\u0412\u0435\u0441')),
                ('is_sweet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('default_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'PREBREAKFAST', '\u041f\u0440\u0435\u0434\u0437\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BREAKFAST', '\u0417\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BRUNCH', '\u0412\u0417'), (b'LUNCH', '\u041e\u0431\u0435\u0434'), (b'MERIENDA', '\u041f\u043e\u043b\u0434\u043d\u0438\u043a'), (b'DINNER', '\u0423\u0436\u0438\u043d'), (b'SNACK', '\u041f\u0435\u0440\u0435\u043a\u0443\u0441')], max_length=25), size=None)),
                ('is_sweet', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='is_validated',
            new_name='is_meal_validated',
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='bed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='faults_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'WAKETOMEAL', '\u041f\u0435\u0440\u0435\u0440\u044b\u0432 \u0434\u043e \u0437\u0430\u0432\u0442\u0440\u0430\u043a\u0430'), (b'FASTSWEET', '\u0421\u043b\u0430\u0434\u043a\u043e\u0435 \u043d\u0430\u0442\u043e\u0449\u0430\u043a'), (b'BREAKTOMEAL', '\u041f\u0435\u0440\u0435\u0440\u044b\u0432 \u043c\u0435\u0436\u0434\u0443 \u043f\u0440\u0438\u0435\u043c\u0430\u043c\u0438 \u043f\u0438\u0449\u0438'), (b'ALCOFOOD', '\u0410\u043b\u043a\u043e\u0433\u043e\u043b\u044c \u0441 \u0437\u0430\u043a\u0443\u0441\u043a\u043e\u0439 / \u0421\u043b\u0430\u0434\u043a\u0438\u0439 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044c'), (b'ALCO2', '\u0411\u043e\u043b\u044c\u0448\u0430\u044f \u043f\u043e\u0440\u0446\u0438\u044f \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f'), (b'SWEET2', '\u0414\u0432\u0430 \u0441\u043b\u0430\u0434\u043a\u0438\u0445 \u043f\u0440\u0438\u0435\u043c\u0430 \u043f\u0438\u0449\u0438, \u043e\u0442\u043e\u0434\u0432\u0438\u043d\u0432\u0443\u0448\u0438\u0445 \u043d\u0435\u0441\u043b\u0430\u0434\u043a\u0438\u0439'), (b'EVENINGSWEET', '\u041f\u043e\u0437\u0434\u043d\u0438\u0435 \u0431\u044b\u0441\u0442\u0440\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'LATECARB', '\u041f\u043e\u0437\u0434\u043d\u0438\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'SLEEPCARB', '\u0421\u043e\u043d \u043f\u043e\u0441\u043b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u043e\u0432'), (b'CUMULATIVE', '\u041d\u0430\u043a\u043e\u043f\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.MealComponentType', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.DiaryMeal'),
        ),
        migrations.AddField(
            model_name='diarymeal',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_times', to='srbc.DiaryRecord'),
        ),
    ]
