# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:31


import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0047_auto_20170627_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcomponenttype',
            name='default_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'PREBREAKFAST', '\u041f\u0440\u0435\u0434\u0437\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BREAKFAST', '\u0417\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BRUNCH', '\u0412\u0417'), (b'LUNCH', '\u041e\u0431\u0435\u0434'), (b'MERIENDA', '\u041f\u043e\u043b\u0434\u043d\u0438\u043a'), (b'DINNER', '\u0423\u0436\u0438\u043d'), (b'SNACK', '\u041f\u0435\u0440\u0435\u043a\u0443\u0441')], max_length=25), blank=True, null=True, size=None),
        ),
    ]
