# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:06


import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0048_auto_20170627_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='tg_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wave',
            name='tg_channel_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='faults_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'WAKETOMEAL', '\u041f\u0435\u0440\u0435\u0440\u044b\u0432 \u0434\u043e \u0437\u0430\u0432\u0442\u0440\u0430\u043a\u0430'), (b'FASTSWEET', '\u0421\u043b\u0430\u0434\u043a\u043e\u0435 \u043d\u0430\u0442\u043e\u0449\u0430\u043a'), (b'BREAKTOMEAL', '\u041f\u0435\u0440\u0435\u0440\u044b\u0432 \u043c\u0435\u0436\u0434\u0443 \u043f\u0440\u0438\u0435\u043c\u0430\u043c\u0438 \u043f\u0438\u0449\u0438'), (b'ALCOFOOD', '\u0410\u043b\u043a\u043e\u0433\u043e\u043b\u044c \u0441 \u0437\u0430\u043a\u0443\u0441\u043a\u043e\u0439 / \u0421\u043b\u0430\u0434\u043a\u0438\u0439 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044c'), (b'ALCO2', '\u0411\u043e\u043b\u044c\u0448\u0430\u044f \u043f\u043e\u0440\u0446\u0438\u044f \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f'), (b'SWEET2', '\u0414\u0432\u0430 \u0441\u043b\u0430\u0434\u043a\u0438\u0445 \u043f\u0440\u0438\u0435\u043c\u0430 \u043f\u0438\u0449\u0438, \u043e\u0442\u043e\u0434\u0432\u0438\u043d\u0432\u0443\u0448\u0438\u0445 \u043d\u0435\u0441\u043b\u0430\u0434\u043a\u0438\u0439'), (b'EVENINGSWEET', '\u041f\u043e\u0437\u0434\u043d\u0438\u0435 \u0431\u044b\u0441\u0442\u0440\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'LATECARB', '\u041f\u043e\u0437\u0434\u043d\u0438\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'FATCARB', '\u0416\u0438\u0440\u043d\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b \u043f\u043e\u0441\u043b\u0435 \u043e\u0431\u0435\u0434\u0430'), (b'SLEEPCARB', '\u0421\u043e\u043d \u043f\u043e\u0441\u043b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u043e\u0432'), (b'CUMULATIVE', '\u041d\u0430\u043a\u043e\u043f\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
