# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0049_auto_20170628_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
