# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0050_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
