# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 18:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0052_auto_20170702_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_link_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_in_club',
            field=models.BooleanField(default=False, verbose_name='\u0412 \u043a\u043b\u0443\u0431\u0435'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_instagram_private',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0442\u044b\u0439 \u0438\u043d\u0441\u0442\u0430\u0433\u0440\u0430\u043c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_perfect_weight',
            field=models.BooleanField(default=False, verbose_name='\u0418\u0434\u0435\u0430\u043b\u044c\u043d\u044b\u0439 \u0432\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='\u0411\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u0430\u044f/\u041a\u043e\u0440\u043c\u044f\u0449\u0430\u044f'),
        ),
    ]
