# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 04:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0053_auto_20170702_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mifit_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
