# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0055_auto_20170703_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreement_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
