# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:03


from django.db import migrations, models
import django.db.models.deletion
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0057_auto_20170708_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryrecord',
            name='meals_data',
        ),
        migrations.RemoveField(
            model_name='mealcomponent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='mealcomponent',
            name='title',
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='description',
            field=models.TextField(default='', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='weight',
            field=srbc.models.DecimalRangeField(decimal_places=3, default=0, max_digits=8, verbose_name='\u0412\u0435\u0441 \u0438\u043b\u0438 \u044d\u043a\u0432\u0438\u0432\u0430\u043b\u0435\u043d\u0442'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_data', to='srbc.DiaryRecord'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='meal_type',
            field=models.CharField(choices=[(b'PREBREAKFAST', '\u041f\u0440\u0435\u0434\u0437\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BREAKFAST', '\u0417\u0430\u0432\u0442\u0440\u0430\u043a'), (b'BRUNCH', '\u0412\u0417'), (b'LUNCH', '\u041e\u0431\u0435\u0434'), (b'MERIENDA', '\u041f\u043e\u043b\u0434\u043d\u0438\u043a'), (b'DINNER', '\u0423\u0436\u0438\u043d'), (b'SNACK', '\u041f\u0435\u0440\u0435\u043a\u0443\u0441'), (b'SLEEP', '\u0414\u043d\u0435\u0432\u043d\u043e\u0439 \u0441\u043e\u043d')], max_length=25),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='component_type',
            field=models.CharField(max_length=50, verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='srbc.DiaryMeal'),
        ),
    ]
