# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0059_auto_20170711_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='\u0412\u0438\u0434\u043d\u043e \u043c\u0430\u0440\u0430\u0444\u043e\u043d\u0446\u0443'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='warning_flag',
            field=models.CharField(choices=[(b'TEST', '\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u043e\u0435 \u043e\u0431\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u0435'), (b'OBSERVATION', '\u0418\u043c\u0435\u044e\u0442\u0441\u044f \u043e\u0441\u043e\u0431\u0435\u043d\u043d\u043e\u0441\u0442\u0438 \u043e\u0431\u043c\u0435\u043d\u0430, \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0435'), (b'TREATMENT', '\u041f\u043e\u0434 \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0435\u043c \u0432\u0440\u0430\u0447\u0435\u0439'), (b'DANGER', '\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u043b\u0435\u0447\u0435\u043d\u0438\u0435, \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0435 \u0432\u0440\u0430\u0447\u0430'), (b'OK', '\u0412\u0441\u0451 \u043e\u043a')], default=b'OK', max_length=20),
        ),
    ]
