# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:04


import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0060_auto_20170712_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramimage',
            name='instagram_account',
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='default_image_url',
            field=models.CharField(default='-', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='image_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='loaded_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 11, 4, 22, 663628)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramimage',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='instagramimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
