# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:28


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0063_auto_20170713_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramimage',
            name='default_image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='instagramimage',
            name='image_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
