# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 01:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0067_auto_20170715_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tracker_brand',
            field=models.CharField(choices=[(b'XIAOMI', 'Xiaomi'), (b'JAWBONE', 'Jawbone'), (b'OTHER', '\u0414\u0440\u0443\u0433\u043e\u0439')], default=b'OTHER', max_length=100),
        ),
    ]
