# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0069_profile_communication_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
