# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 17:56


from django.db import migrations
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0070_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='dairy_consumed',
            field=srbc.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
