# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 17:27


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0073_remove_diaryrecord_faults_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymeal',
            name='faults_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='faults_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='faults_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
