# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 19:52


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0074_auto_20170806_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='is_locked',
            new_name='is_meal_reviewed',
        ),
    ]
