# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 16:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0079_auto_20170819_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_update_required',
            field=models.BooleanField(default=False),
        ),
    ]
