# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 16:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0080_profile_instagram_update_required'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instagramimage',
            index=models.Index(fields=['image_id'], name='srbc_instag_image_i_760e7f_idx'),
        ),
    ]
