# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 17:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0081_auto_20170819_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
