# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 18:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0082_instagramimage_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instagramimage',
            index=models.Index(fields=['tags'], name='srbc_instag_tags_93a6f1_idx'),
        ),
    ]
