# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 08:38


from django.db import migrations, models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0084_auto_20170826_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointrecord',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkpointrecord',
            name='front_image',
            field=models.ImageField(upload_to=srbc.models.checkpoint_face_image_upload_to),
        ),
        migrations.AlterField(
            model_name='checkpointrecord',
            name='rear_image',
            field=models.ImageField(upload_to=srbc.models.checkpoint_rear_image_upload_to),
        ),
        migrations.AlterField(
            model_name='checkpointrecord',
            name='side_image',
            field=models.ImageField(upload_to=srbc.models.checkpoint_side_image_upload_to),
        ),
    ]
