# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 19:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0086_auto_20170827_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointrecord',
            name='front_image_hash',
        ),
        migrations.RemoveField(
            model_name='checkpointrecord',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='checkpointrecord',
            name='rear_image_hash',
        ),
        migrations.RemoveField(
            model_name='checkpointrecord',
            name='side_image_hash',
        ),
        migrations.AddField(
            model_name='checkpointrecord',
            name='status',
            field=models.CharField(choices=[(b'NEW', '\u041d\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), (b'APPROVED', '\u041e\u0434\u043e\u0431\u0440\u0435\u043d\u044b'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u044b')], default=b'NEW', max_length=20),
        ),
    ]
