# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 04:15


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0088_diaryrecord_is_fake_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_is_in_channel',
        ),
    ]
