# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 18:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0092_auto_20170907_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_year',
            field=models.IntegerField(default=2017, verbose_name='\u0413\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
