# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 19:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0094_auto_20170909_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0412\u0430\u0448 \u0432\u043e\u0437\u0440\u0430\u0441\u0442'),
        ),
    ]
