# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 20:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0098_auto_20170927_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='days_paid',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
    ]
