# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 21:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0099_invitation_days_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043d\u043a\u0435\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u0430\u043a\u0442\u0438\u0432\u0435\u043d'),
        ),
    ]
