# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 09:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0101_auto_20171001_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_self_meal_formula',
            field=models.BooleanField(default=False, verbose_name='C\u0430\u043c\u043e\u043e\u0446\u0438\u0444\u0440\u043e\u0432\u043a\u0430'),
        ),
    ]
