# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 18:23


from django.db import migrations, models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0103_diaryrecord_meal_validation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='widgets_display',
            field=srbc.models.ChoiceArrayField(base_field=models.CharField(choices=[(b'NOTES', '\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0435 \u0440\u0435\u043a\u043e\u043c\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u0438'), (b'CALENDAR', '\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044c \u0434\u0430\u043d\u043d\u044b\u0445'), (b'MEETINGS', '\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 \u043c\u0438\u0442\u0438\u043d\u0433\u0438'), (b'ALARM', '\u0410\u043b\u044f\u0440\u043c'), (b'CHARTS', '\u0413\u0440\u0430\u0444\u0438\u043a\u0438 \u0441 \u0434\u0430\u043d\u043d\u044b\u043c\u0438')], max_length=50), blank=True, default=[], size=None),
        ),
    ]
