# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 11:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0106_auto_20171112_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='communication_mode',
            field=models.CharField(blank=True, choices=[(b'CHANNEL', '\u041a\u0430\u043d\u0430\u043b'), (b'CHAT', '\u0427\u0430\u0442')], max_length=20, null=True),
        ),
    ]
