# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 23:57


from django.db import migrations, models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0108_auto_20171116_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTwoWeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('trueweight_start', srbc.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('trueweight_end', srbc.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight_start', srbc.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight_end', srbc.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('steps_days', models.PositiveIntegerField(blank=True, null=True)),
                ('steps_ok_days', models.PositiveIntegerField(blank=True, null=True)),
                ('overcalory_days', models.PositiveIntegerField(blank=True, null=True)),
                ('ooc_days', models.PositiveIntegerField(blank=True, null=True)),
                ('faulty_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meals_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meals_bad_days', models.PositiveIntegerField(blank=True, null=True)),
                ('alco_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile_2week_stat',
                'managed': False,
            },
        ),
    ]
