# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 14:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0109_profiletwoweekstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAnalizeFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['date_added'], name='srbc_userno_date_ad_9c665d_idx'),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['is_published'], name='srbc_userno_is_publ_7f7b38_idx'),
        ),
        migrations.AddIndex(
            model_name='autoanalizeformula',
            index=models.Index(fields=['code'], name='srbc_autoan_code_9c4b4d_idx'),
        ),
    ]
