# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 14:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0111_auto_20171202_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoanalizeformula',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
