# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0115_profile_admission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='meal_last_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='meal_status',
            field=models.CharField(choices=[(b'NOT_READY', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f'), (b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043e\u0446\u0438\u0444\u0440\u043e\u0432\u043a\u0438'), (b'OK', '\u041e\u0446\u0438\u0444\u0440\u043e\u0432\u0430\u043d'), (b'OOC', '\u0412\u043d\u0435 \u043a\u043e\u043d\u0446\u0435\u043f\u0446\u0438\u0438'), (b'NA_WARN', '\u041d\u0435\u0442 \u0434\u0430\u043d\u043d\u044b\u0445, \u043f\u0440\u0435\u0434\u0443\u043f\u0440\u0435\u0436\u0434\u0451\u043d'), (b'NA', '\u041d\u0435\u0442 \u0434\u0430\u043d\u043d\u044b\u0445'), (b'FAKE', '\u0414\u0430\u043d\u043d\u044b\u0435 \u043d\u0435\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u043d\u044b')], default=b'NOT_READY', max_length=50),
        ),
    ]
