# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 19:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0123_auto_20180120_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='height',
            field=models.IntegerField(default=0, verbose_name='\u0412\u0430\u0448 \u0440\u043e\u0441\u0442'),
        ),
    ]
