# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 19:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0125_auto_20180120_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='birth_year',
            field=models.IntegerField(null=True, verbose_name='\u0413\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='application',
            name='goals',
            field=models.TextField(null=True, verbose_name='\u0426\u0435\u043b\u0438 \u043d\u0430 \u043c\u0430\u0440\u0430\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sickness',
            field=models.TextField(null=True, verbose_name='\u0418\u043c\u0435\u044e\u0449\u0438\u0435\u0441\u044f \u0437\u0430\u0431\u043e\u043b\u0435\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
