# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 09:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0126_auto_20180120_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryMealFault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
