# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 10:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0127_diarymealfault'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='social_acc_status',
            field=models.CharField(blank=True, choices=[(b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f'), (b'APPROVED', '\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'), (b'SUSPICIOUS', '\u041f\u043e\u0434\u043e\u0437\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0451\u043d')], default=b'PENDING', max_length=25),
        ),
    ]
