# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 10:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0129_application_admission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admission_status',
        ),
    ]
