# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 11:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0131_gttresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gttresult',
            name='glucose_unit',
            field=models.CharField(choices=[(b'MG_DL', '\u043c\u0433/\u0434\u043b'), (b'MM_L', '\u043c\u043c\u043e\u043b\u044c/\u043b')], default='MM_L', max_length=50),
            preserve_default=False,
        ),
    ]
