# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 17:02


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0132_gttresult_glucose_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL),
        ),
    ]
