# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 05:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0135_auto_20180220_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tos_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
