# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 15:12


import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0136_application_tos_signed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRBCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image_type', models.CharField(choices=[(b'MEAL', '\u0420\u0430\u0446\u0438\u043e\u043d'), (b'DATA', '\u0414\u0430\u043d\u043d\u044b\u0435'), (b'CHECKPOINT_PHOTO', '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e'), (b'CHECKPOINT_PHOTO_FACE', '\u0421\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e - \u0430\u043d\u0444\u0430\u0441'), (b'CHECKPOINT_PHOTO_SIDE', '\u0421\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e - \u0441\u0431\u043e\u043a\u0443'), (b'CHECKPOINT_PHOTO_REAR', '\u0421\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e - \u0441\u0437\u0430\u0434\u0438'), (b'CHECKPOINT_MEASUREMENTS', '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u043c\u0435\u0440\u044b'), (b'CHECKPOINT_CHARTS', '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0439 TrueWeight')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=srbc.models.srbc_image_upload_to)),
                ('is_editable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
