# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 11:35


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0139_auto_20180305_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_payment_allowed',
            field=models.BooleanField(default=False, verbose_name='\u0420\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u0430 \u043e\u043f\u043b\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='application',
            name='active_payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Order'),
        ),
    ]
