# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 13:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0141_auto_20180311_2051'),
    ]

    database_operations = [
        migrations.AlterModelTable('Application', 'crm_application'),
    ]

    state_operations = [
        migrations.DeleteModel('Application'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]