# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 20:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0142_auto_20180318_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoanalizeformula',
            options={'verbose_name': '\u0444\u043e\u0440\u043c\u0443\u043b\u0430 \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u0430\u043d\u0430\u043b\u0438\u0437\u0430', 'verbose_name_plural': '\u0444\u043e\u0440\u043c\u0443\u043b\u044b \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u0430\u043d\u0430\u043b\u0438\u0437\u0430'},
        ),
        migrations.AlterModelOptions(
            name='checkpointrecord',
            options={'verbose_name': '\u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u0430\u044f \u0442\u043e\u0447\u043a\u0430', 'verbose_name_plural': '\u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0447\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='srbcimage',
            options={'verbose_name': '\u0424\u043e\u0442\u043e-\u043b\u0435\u043d\u0442\u0430', 'verbose_name_plural': '\u0424\u043e\u0442\u043e-\u043b\u0435\u043d\u0442\u0430'},
        ),
        migrations.AlterModelOptions(
            name='usernote',
            options={'verbose_name': '\u0437\u0430\u043c\u0435\u0442\u043a\u0430 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430', 'verbose_name_plural': '\u0437\u0430\u043c\u0435\u0442\u043a\u0438 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432'},
        ),
    ]
