# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 13:18


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0144_auto_20180325_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrecord',
            name='meal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiaryMeadFood', to='srbc.SRBCImage'),
        ),
    ]
