# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 21:46


from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0143_auto_20180318_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryRecordCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('trueweight', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('sleep', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('steps', shared.models.IntegerRangeField(blank=True, null=True)),
                ('meals', shared.models.IntegerRangeField(blank=True, null=True)),
                ('faults', shared.models.IntegerRangeField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_perfect_weight', models.BooleanField(default=False)),
                ('is_sick', models.BooleanField(default=False)),
                ('is_meal_validated', models.BooleanField(default=False)),
                ('meal_validation_date', models.DateTimeField(blank=True, null=True)),
                ('is_meal_reviewed', models.BooleanField(default=False)),
                ('is_overcalory', models.BooleanField(default=False)),
                ('is_mono', models.BooleanField(default=False)),
                ('is_unload', models.BooleanField(default=False)),
                ('is_ooc', models.BooleanField(default=False)),
                ('is_na_meals', models.BooleanField(default=False)),
                ('is_fake_meals', models.BooleanField(default=False)),
                ('is_na_data', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('meal_status', models.CharField(choices=[(b'NOT_READY', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f'), (b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043e\u0446\u0438\u0444\u0440\u043e\u0432\u043a\u0438'), (b'VALIDATION', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438 \u043e\u0446\u0438\u0444\u0440\u043e\u0432\u043a\u0438'), (b'FEEDBACK', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043e\u0442\u0432\u0435\u0442\u0430'), (b'DONE', '\u041e\u0446\u0438\u0444\u0440\u043e\u0432\u0430\u043d'), (b'NA_WARN', '\u041d\u0435\u0442 \u0434\u0430\u043d\u043d\u044b\u0445, \u043f\u0440\u0435\u0434\u0443\u043f\u0440\u0435\u0436\u0434\u0451\u043d'), (b'NA', '\u041d\u0435\u0442 \u0434\u0430\u043d\u043d\u044b\u0445'), (b'FAKE', '\u0414\u0430\u043d\u043d\u044b\u0435 \u043d\u0435\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u043d\u044b')], default=b'NOT_READY', max_length=50)),
                ('meal_last_status_date', models.DateTimeField(blank=True, null=True)),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('bed_time', models.TimeField(blank=True, null=True)),
                ('bed_time_is_next_day', models.BooleanField(default=False)),
                ('water_consumed', shared.models.DecimalRangeField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dairy_consumed', shared.models.IntegerRangeField(blank=True, null=True)),
                ('faults_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                ('has_meal_faults', models.BooleanField(default=False)),
                ('data_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiaryCopyImageData', to='srbc.InstagramImage')),
                ('meal_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiaryCopyImageFood', to='srbc.InstagramImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries_copy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='diaryrecordcopy',
            index=models.Index(fields=['user', 'date'], name='srbc_diaryr_user_id_c48f92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diaryrecordcopy',
            unique_together=set([('user', 'date')]),
        ),
    ]
