# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 03:14


from django.db import migrations, models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0144_auto_20180320_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbcimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.srbc_image_upload_to),
        ),
    ]
