# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 03:33


from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0146_auto_20180322_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbcimage',
            name='image_info',
            field=markdownx.models.MarkdownxField(blank=True, default=None, null=True),
        ),
    ]
