# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 20:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0145_auto_20180327_0046'),
        ('srbc', '0144_auto_20180325_1931'),
        ('srbc', '0147_auto_20180328_0633'),
    ]

    operations = [
    ]
