# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 21:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0148_merge_20180328_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbcimage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='srbcimage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='srbcimage',
            index=models.Index(fields=['user'], name='srbc_srbcim_user_id_c311c7_idx'),
        ),
        migrations.AddIndex(
            model_name='srbcimage',
            index=models.Index(fields=['date'], name='srbc_srbcim_date_1e7ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='srbcimage',
            index=models.Index(fields=['image_type'], name='srbc_srbcim_image_t_3465a5_idx'),
        ),
        migrations.AddIndex(
            model_name='srbcimage',
            index=models.Index(fields=['is_published'], name='srbc_srbcim_is_publ_7052d7_idx'),
        ),
    ]
