# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 16:31


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0153_auto_20180402_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealproduct',
            name='verified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
