# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 17:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0154_auto_20180402_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='replacement_title',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430 \u0437\u0430\u043c\u0435\u043d\u0443'),
        ),
    ]
