# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 18:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0155_mealproduct_replacement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='is_ingredients_required',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c \u0441\u043e\u0441\u0442\u0430\u0432'),
        ),
        migrations.AddField(
            model_name='mealproduct',
            name='is_nutrition_required',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c \u0411\u0416\u0423'),
        ),
    ]
