# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-06 18:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0158_auto_20180404_1759'),
        ('srbc', '0152_auto_20180401_1855'),
    ]

    operations = [
    ]
