# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 05:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0159_merge_20180406_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckpointRecord',
            new_name='CheckpointPhotos',
        ),
    ]
