# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-08 09:13


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0160_auto_20180407_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('measurement_point_01', models.IntegerField(blank=True, null=True)),
                ('measurement_point_02', models.IntegerField(blank=True, null=True)),
                ('measurement_point_03', models.IntegerField(blank=True, null=True)),
                ('measurement_point_04', models.IntegerField(blank=True, null=True)),
                ('measurement_point_05', models.IntegerField(blank=True, null=True)),
                ('measurement_point_06', models.IntegerField(blank=True, null=True)),
                ('measurement_point_07', models.IntegerField(blank=True, null=True)),
                ('measurement_point_08', models.IntegerField(blank=True, null=True)),
                ('measurement_point_09', models.IntegerField(blank=True, null=True)),
                ('measurement_point_10', models.IntegerField(blank=True, null=True)),
                ('measurement_point_11', models.IntegerField(blank=True, null=True)),
                ('measurement_point_12', models.IntegerField(blank=True, null=True)),
                ('measurement_point_13', models.IntegerField(blank=True, null=True)),
                ('measurement_point_14', models.IntegerField(blank=True, null=True)),
                ('measurement_point_15', models.IntegerField(blank=True, null=True)),
                ('measurement_point_16', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_01',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_02',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_03',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_04',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_05',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_06',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_07',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_08',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_09',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_10',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_11',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_12',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_13',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_14',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_15',
        ),
        migrations.RemoveField(
            model_name='checkpointphotos',
            name='measurement_point_16',
        ),
        migrations.AlterField(
            model_name='checkpointphotos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkpointphotos',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.Checkpoint'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['user', 'date'], name='idx_checkpoint_user_date'),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together=set([('user', 'date')]),
        ),
    ]
