# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 06:20


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0161_auto_20180408_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointphotos',
            name='crop_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
