# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 06:26


from django.db import migrations, models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0162_checkpointphotos_crop_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointphotos',
            name='front_image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.checkpoint_face_image_upload_to),
        ),
        migrations.AddField(
            model_name='checkpointphotos',
            name='rear_image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.checkpoint_rear_image_upload_to),
        ),
        migrations.AddField(
            model_name='checkpointphotos',
            name='side_image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.checkpoint_side_image_upload_to),
        ),
        migrations.AlterField(
            model_name='checkpointphotos',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.checkpoint_face_image_upload_to),
        ),
        migrations.AlterField(
            model_name='checkpointphotos',
            name='rear_image',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.checkpoint_rear_image_upload_to),
        ),
        migrations.AlterField(
            model_name='checkpointphotos',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.checkpoint_side_image_upload_to),
        ),
    ]
