# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 19:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0166_auto_20180414_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='is_measurements_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='is_photo_done',
            field=models.BooleanField(default=False),
        ),
    ]
