# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-18 15:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0166_auto_20180414_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srbcimage',
            name='image_type',
            field=models.CharField(choices=[(b'MEAL', '\u0420\u0430\u0446\u0438\u043e\u043d'), (b'DATA', '\u0414\u0430\u043d\u043d\u044b\u0435'), (b'CHECKPOINT_PHOTO', '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e'), (b'CHECKPOINT_PHOTO_FRONT', '\u0421\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e - \u0430\u043d\u0444\u0430\u0441'), (b'CHECKPOINT_PHOTO_SIDE', '\u0421\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e - \u0441\u0431\u043e\u043a\u0443'), (b'CHECKPOINT_PHOTO_REAR', '\u0421\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e - \u0441\u0437\u0430\u0434\u0438'), (b'CHECKPOINT_MEASUREMENTS', '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u043c\u0435\u0440\u044b'), (b'CHECKPOINT_CHARTS', '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0439 TrueWeight')], max_length=100),
        ),
    ]
