# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-18 19:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0167_auto_20180418_1832'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkpoint',
            name='idx_checkpoint_user_date',
        ),
        migrations.AddField(
            model_name='srbcimage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together=set([]),
        ),
    ]
