# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-18 19:57


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0168_auto_20180418_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbcimage',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
