# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-30 12:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0169_srbcimage_meta_data'),
        ('srbc', '0167_auto_20180416_2203'),
    ]

    operations = [
    ]
