# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 14:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0171_auto_20180516_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
