# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 10:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0171_auto_20180601_1752'),
        ('srbc', '0171_auto_20180516_1526'),
    ]

    operations = [
    ]
