# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 08:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0171_auto_20180601_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
