# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-05 10:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0173_auto_20180626_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='is_notification_sent',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0435 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e'),
        ),
    ]
