# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-13 11:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0177_auto_20180713_1433'),
        ('srbc', '0172_auto_20180629_1140'),
    ]

    operations = [
    ]
