# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 08:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0178_merge_20180713_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealFault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, default=b'')),
                ('code', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DiaryMealFault',
        ),
    ]
