# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 17:05


from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Profile = apps.get_model('srbc', 'Profile')
    Checkpoint = apps.get_model('srbc', 'Checkpoint')

    for user_id, profile_height in Profile.objects.values_list('user_id', 'height').iterator():
        if profile_height:
            Checkpoint.objects.filter(user_id=user_id).update(measurement_height=profile_height*10)


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0178_merge_20180713_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='measurement_height',
            field=models.IntegerField(blank=True, null=True),
        ),

        migrations.RunPython(set_my_defaults, reverse_code=migrations.RunPython.noop),
    ]
