# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 14:06


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0180_diarymealfault'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfault',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diarymealfault',
            name='diary_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults_list', to='srbc.DiaryRecord'),
        ),
    ]
