# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 18:07


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0181_auto_20180803_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfault',
            name='scopes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
