# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 15:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0182_mealfault_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfault',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
