# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-10 11:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0184_profile_is_meal_comments_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymealfault',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
