# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 09:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0179_auto_20180813_2005'),
        ('srbc', '0185_auto_20180810_1445'),
    ]

    operations = [
    ]
