# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 07:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0187_auto_20180823_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
