# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 09:47


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0190_auto_20180907_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fee_rub', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fee_eur', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('communication_mode', models.CharField(blank=True, choices=[(b'CHANNEL', '\u041a\u0430\u043d\u0430\u043b'), (b'CHAT', '\u0427\u0430\u0442')], max_length=20, null=True)),
                ('renewal_mode', models.CharField(choices=[(b'AUTO', '\u0410\u0432\u0442\u043e-\u043f\u0440\u043e\u0434\u043b\u0435\u043d\u0438\u0435'), (b'APPROVED', '\u0410\u0432\u0442\u043e-\u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435'), (b'MANUAL', '\u0420\u0443\u0447\u043d\u043e\u0435 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435')], max_length=25)),
                ('tariff_next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.Tariff')),
            ],
        ),
        migrations.CreateModel(
            name='TariffAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TariffPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.IntegerField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.TariffAction')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.Tariff')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='srbc.Tariff'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants_next', to='srbc.Tariff'),
        ),
    ]
