# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 09:49


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0191_auto_20180921_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.Tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
