# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 11:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0192_tariffhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c (\u0432 \u0434\u043d\u044f\u0445)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='fee_eur',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c (EUR)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='fee_rub',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c (RUB)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='slug',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_next',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.Tariff', verbose_name='\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0438\u0439 \u0442\u0430\u0440\u0438\u0444'),
        ),
    ]
