# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 11:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0193_auto_20180921_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='duration_unit',
            field=models.CharField(choices=[(b'DAY', '\u0414\u043d\u0438'), (b'WEEK', '\u041d\u0435\u0434\u0435\u043b\u0438'), (b'MONTH', '\u041c\u0435\u0441\u044f\u0446\u044b')], default=b'DAY', max_length=25),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
