# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 11:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0194_auto_20180921_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.Tariff', verbose_name='\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0438\u0439 \u0442\u0430\u0440\u0438\u0444'),
        ),
    ]
