# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-19 07:38


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0198_auto_20181016_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='chart_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
