# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 13:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0200_auto_20181022_1429'),
        ('srbc', '0191_auto_20180913_2040'),
    ]

    operations = [
    ]
