# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-02 05:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0201_auto_20181030_1354'),
        ('srbc', '0191_auto_20180913_2040'),
    ]

    operations = [
    ]
