# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-13 08:48


from django.db import migrations, models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0201_merge_20181108_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymeal',
            name='meal_image',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.diary_meal_image_upload_to),
        ),
    ]
