# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-09 10:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0203_auto_20181109_1313'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealproduct',
            index=models.Index(fields=['aliases'], name='srbc_mealpr_aliases_4f36cc_idx'),
        ),
    ]
