# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-21 08:18


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0203_auto_20181106_1650'),
        ('srbc', '0202_auto_20181116_1148'),
        ('srbc', '0204_auto_20181109_1321'),
    ]

    operations = [
    ]
