# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-23 13:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0205_merge_20181121_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcomponent',
            name='details_carb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='details_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='details_protein',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='details_sugars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='other_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
