# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-06 09:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0206_auto_20181123_1623'),
        ('srbc', '0186_merge_20180816_1249'),
        ('srbc', '0208_auto_20190121_1431'),
    ]

    operations = [
    ]
