# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-06 20:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0208_auto_20190121_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='adjust_fruits',
            field=models.CharField(blank=True, choices=[(b'NO', '\u0411\u0435\u0437 \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u0439'), (b'RESTRICT', '\u041c\u0438\u043d\u0438\u043c\u0438\u0437\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u0440\u0446\u0438\u044e \u0444\u0440\u0443\u043a\u0442\u043e\u0432'), (b'EXCLUDE', '\u0417\u0430\u043c\u0435\u043d\u0438\u0442\u044c \u0444\u0440\u0443\u043a\u0442\u044b \u043d\u0430 \u043e\u0432\u043e\u0449\u0438 \u0438\u043b\u0438 \u043d\u0435\u0441\u043b\u0430\u0434\u043a\u0438\u0435 \u043a\u0440\u0435\u043a\u0435\u0440\u044b')], default=b'NO', max_length=20),
        ),
    ]
