# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 08:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0209_auto_20190206_2304'),
        ('srbc', '0209_merge_20190206_1251'),
    ]

    operations = [
    ]
