# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 09:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0210_merge_20190220_1157'),
        ('srbc', '0210_auto_20190220_1512'),
    ]

    operations = [
    ]
