# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 10:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0211_auto_20190221_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealproduct',
            name='fast_carb_percent',
        ),
    ]
