# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-01 07:24


from django.db import migrations
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0212_auto_20190228_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_weight',
            field=shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='\u0426\u0435\u043b\u0435\u0432\u043e\u0439 \u0432\u0435\u0441'),
        ),
    ]
