# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-01 07:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0213_profile_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_goal_weight',
            field=models.BooleanField(default=True),
        ),
    ]
