# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-01 13:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0212_remove_mealproduct_fast_carb_percent'),
        ('srbc', '0214_profile_display_goal_weight'),
    ]

    operations = [
    ]
