# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-27 06:09


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0218_auto_20190326_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealProductModeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'PENDING', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), (b'APPROVED_NEW', '\u041d\u043e\u0432\u044b\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0442'), (b'APPROVED_ALIAS', '\u0421\u0438\u043d\u043e\u043d\u0438\u043c'), (b'REJECTED', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u043e')], default=b'PENDING', max_length=50)),
                ('component_type', models.CharField(blank=True, choices=[(b'bread', '\u0425\u043b\u0435\u0431'), (b'fat', '\u0416\u0438\u0440\u043d\u044b\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0442'), (b'carb', '\u0413\u043e\u0442\u043e\u0432\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'rawcarb', '\u0421\u0443\u0445\u0438\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'fatcarb', '\u0416\u0438\u0440\u043d\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'), (b'protein', '\u0411\u0435\u043b\u043a\u043e\u0432\u044b\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0442'), (b'deadweight', '\u0411\u0430\u043b\u043b\u0430\u0441\u0442'), (b'veg', '\u041e\u0432\u043e\u0449\u0438'), (b'carbveg', '\u0417\u0430\u043f\u0430\u0441\u0430\u044e\u0449\u0438\u0435 \u043e\u0432\u043e\u0449\u0438'), (b'fruit', '\u0424\u0440\u0443\u043a\u0442\u044b'), (b'dfruit', '\u0421\u0443\u0445\u043e\u0444\u0440\u0443\u043a\u0442\u044b'), (b'desert', '\u0414\u0435\u0441\u0435\u0440\u0442'), (b'drink', '\u041a\u0430\u043b\u043e\u0440\u0438\u0439\u043d\u044b\u0439 \u043d\u0430\u043f\u0438\u0442\u043e\u043a'), (b'alco', '\u0410\u043b\u043a\u043e\u0433\u043e\u043b\u044c'), (b'unknown', '\u041f\u0440\u043e\u0434\u0443\u043a\u0442 \u0441 \u043d\u0435\u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043d\u044b\u043c \u0441\u043e\u0441\u0442\u0430\u0432\u043e\u043c'), (b'mix', '\u0421\u043b\u043e\u0436\u043d\u0430\u044f \u0441\u043c\u0435\u0441\u044c')], default=None, max_length=50, null=True, verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
                ('title_source', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.MealProduct')),
                ('meal_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.MealComponent')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
