# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-27 09:28


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.models
import srbc.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0219_mealproductmoderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymeal',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='is_overcalory',
            field=models.BooleanField(default=False, verbose_name='\u0418\u0437\u0431\u044b\u0442\u043e\u043a \u043a\u0430\u043b\u043e\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='is_sweet',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0430\u0445\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='meal_image',
            field=models.ImageField(blank=True, null=True, upload_to=srbc.models.diary_meal_image_upload_to, verbose_name='\u0424\u043e\u0442\u043e \u0440\u0430\u0446\u0438\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='diarymeal',
            name='start_time',
            field=models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='bed_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u0431\u043e\u044f'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='date',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='meal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_record', to='srbc.SRBCImage', verbose_name='\u041a\u043e\u043b\u043b\u0430\u0436 \u043f\u0438\u0435\u043c\u043e\u0432 \u043f\u0438\u0449\u0438'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='meals',
            field=shared.models.IntegerRangeField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0446\u0435\u043d\u043d\u043e\u0441\u0442\u044c \u0440\u0430\u0446\u0438\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='sleep',
            field=shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='\u0421\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='steps',
            field=shared.models.IntegerRangeField(blank=True, null=True, verbose_name='\u0428\u0430\u0433\u0438'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='trueweight',
            field=shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='TrueWeight'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='wake_up_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u043e\u0431\u0443\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='water_consumed',
            field=shared.models.DecimalRangeField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u043d\u043e\u0439 \u0432\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='weight',
            field=shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='\u0412\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='details_carb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='\u0423\u0433\u043b\u0435\u0432\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='details_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='\u0416\u0438\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='details_protein',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='\u0411\u0435\u043b\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='details_sugars',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0431\u044b\u0441\u0442\u0440\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='external_link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='other_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0414\u0440\u0443\u0433\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='carb_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='\u0423\u0433\u043b\u0435\u0432\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='fat_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='\u0416\u0438\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='is_alco',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='is_fast_carbs',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0431\u044b\u0441\u0442\u0440\u044b\u0435 \u0443\u0433\u043b\u0435\u0432\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='is_generic',
            field=models.BooleanField(default=False, verbose_name='"\u041f\u0440\u043e\u0447\u0435\u0435" \u0432 \u0441\u0432\u043e\u0435\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='protein_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='\u0411\u0435\u043b\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='mealproductmoderation',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
