# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 21:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0220_auto_20190327_1228'),
        ('srbc', '0213_auto_20190321_1647'),
    ]

    operations = [
    ]
