# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-06 03:25


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0223_auto_20190401_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymeal',
            name='img_meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
