# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 08:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0224_auto_20190514_1521'),
        ('srbc', '0224_auto_20190406_0625'),
    ]

    operations = [
    ]
