# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-19 13:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0225_merge_20190520_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymeal',
            name='meal_image_status',
            field=models.CharField(blank=True, choices=[(b'CORRECT', '\u0424\u043e\u0442\u043e \u0437\u0430 \u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u044b\u0439 \u0434\u0435\u043d\u044c'), (b'FAKE_DATE', '\u0424\u043e\u0442\u043e \u0437\u0430 \u043d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u044b\u0439 \u0434\u0435\u043d\u044c'), (b'FAKE_NO_DATE', '\u0424\u043e\u0442\u043e \u0431\u0435\u0437 EXIF \u0434\u0430\u043d\u043d\u044b\u0445')], default=b'CORRECT', max_length=20),
        ),
    ]
