# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-20 08:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0227_auto_20190716_2226'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['stat_group'], name='srbc_profil_stat_gr_0c995f_idx'),
        ),
    ]
