# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-20 08:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0228_auto_20190720_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='wave',
            index=models.Index(fields=['title'], name='srbc_wave_title_20fbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='wave',
            index=models.Index(fields=['is_in_club'], name='srbc_wave_is_in_c_2bca33_idx'),
        ),
    ]
