# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-21 19:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0230_auto_20190720_1135'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='srbc_profil_data_se_611c12_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='data_sergeant',
        ),
    ]
