# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-23 09:59


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0232_diaryrecord_pers_rec_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='meal_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaries_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='diaryrecord',
            index=models.Index(fields=['meal_status'], name='srbc_diaryr_meal_st_a23ff5_idx'),
        ),
    ]
