# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-23 10:35


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0233_auto_20190723_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
