# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-23 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0234_auto_20190723_1335'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealfault',
            index=models.Index(fields=['is_active'], name='srbc_mealfa_is_acti_bcb52b_idx'),
        ),
        migrations.AddIndex(
            model_name='mealfault',
            index=models.Index(fields=['code'], name='srbc_mealfa_code_b97d48_idx'),
        ),
    ]
