# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-24 18:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0235_auto_20190723_1851'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diaryrecord',
            index=models.Index(fields=['is_fake_meals'], name='srbc_diaryr_is_fake_ef1d23_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryrecord',
            index=models.Index(fields=['meal_last_status_date'], name='srbc_diaryr_meal_la_56c230_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryrecord',
            index=models.Index(fields=['meal_reviewed_by'], name='srbc_diaryr_meal_re_a6bd4e_idx'),
        ),
    ]
