# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 06:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0237_mealfault_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='alco_prc',
            field=models.FloatField(blank=True, default=0, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f (%)'),
        ),
        migrations.AddField(
            model_name='mealproduct',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0440\u043d\u0430\u044f \u043a\u0430\u043b\u043e\u0440\u0438\u0439\u043d\u043e\u0441\u0442\u044c (\u043d\u0430 100\u0433)'),
        ),
    ]
