# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 06:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0238_auto_20190725_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealproduct',
            name='is_generic',
        ),
    ]
