# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 10:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0239_remove_mealproduct_is_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfault',
            name='short_title',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
    ]
