# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-29 15:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0240_mealfault_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealproduct',
            name='alco_prc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435 \u0430\u043b\u043a\u043e\u0433\u043e\u043b\u044f (%)'),
        ),
    ]
