# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-30 08:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0241_auto_20190729_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='glucose_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='\u0413\u043b\u044e\u043a\u043e\u0437\u043d\u044b\u0439 \u044d\u043a\u0432\u0438\u0432\u0430\u043b\u0435\u043d\u0442 (\u043d\u0430 100\u0433)'),
        ),
    ]
