# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-30 10:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0242_mealproduct_glucose_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealproduct',
            name='carb_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, verbose_name='\u0423\u0433\u043b\u0435\u0432\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='fat_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, verbose_name='\u0416\u0438\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='mealproduct',
            name='protein_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, verbose_name='\u0411\u0435\u043b\u043a\u0438'),
        ),
    ]
