# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-05 11:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0246_auto_20190802_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpointphotos',
            options={'verbose_name': '\u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e', 'verbose_name_plural': '\u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0442\u043e'},
        ),
    ]
