# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-05 17:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0247_auto_20190805_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='slug',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
