# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-28 11:42


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0249_auto_20190812_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[(b'NEW', '\u041d\u043e\u0432\u0430\u044f'), (b'REACHED', '\u0414\u043e\u0441\u0442\u0438\u0433\u043d\u0443\u0442\u0430\u044f'), (b'DELETED', '\u0423\u0434\u0430\u043b\u0435\u043d\u0430\u044f')], default=b'NEW', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status_changed_on', models.DateTimeField()),
                ('ordernum', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordernum', 'created_on'],
            },
        ),
    ]
