# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-30 12:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0250_auto_20190901_1233'),
        ('srbc', '0250_auto_20190827_2125'),
    ]

    operations = [
    ]
