# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-30 18:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0252_auto_20190930_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarymeal',
            options={'permissions': (('manage_diary_meal', 'Manage Diary Meal'),)},
        )
    ]
