# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 02:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0252_auto_20191021_1719'),
        ('srbc', '0250_auto_20190828_1442'),
        ('srbc', '0252_auto_20190930_1534'),
    ]

    operations = [
    ]
