# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-15 10:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0253_auto_20191114_1637'),
        ('srbc', '0253_auto_20191030_2142'),
        ('srbc', '0254_auto_20191101_0520'),
    ]

    operations = [
    ]
