# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-06 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0255_auto_20191115_1650'),
        ('srbc', '0255_merge_20191115_1348'),
    ]

    operations = [
    ]
