# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0256_merge_20191206_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealproduct',
            name='starch_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='\u041a\u0440\u0430\u0445\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u044d\u043a\u0432\u0438\u0432\u0430\u043b\u0435\u043d\u0442 (\u043d\u0430 100\u0433)'),
        ),
    ]
