# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0257_mealproduct_starch_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u0433')),
                ('system_code', models.CharField(max_length=50, unique=True, verbose_name='\u041a\u043e\u0434')),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='srbc.MealProduct', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b')),
            ],
            options={
                'verbose_name': '\u0442\u044d\u0433 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430',
                'verbose_name_plural': '\u0442\u044d\u0433\u0438 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u0432',
            },
        ),
    ]
