# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0258_mealproducttag'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealproduct',
            name='srbc_mealpr_aliases_4f36cc_idx',
        ),
        migrations.RemoveField(
            model_name='mealproduct',
            name='aliases',
        ),
        migrations.AlterField(
            model_name='mealproductalias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='srbc.MealProduct'),
        ),
    ]
