# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-28 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0260_auto_20191224_1318'),
        ('srbc', '0258_auto_20200115_1356'),
    ]

    operations = [
    ]
