# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-12 04:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0262_auto_20200228_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTwoWeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('trueweight_start',
                 shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('trueweight_end',
                 shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                (
                'weight_start', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight_end', shared.models.DecimalRangeField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('steps_days', models.PositiveIntegerField(blank=True, null=True)),
                ('steps_ok_days', models.PositiveIntegerField(blank=True, null=True)),
                ('overcalory_days', models.PositiveIntegerField(blank=True, null=True)),
                ('ooc_days', models.PositiveIntegerField(blank=True, null=True)),
                ('faulty_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meals_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meals_bad_days', models.PositiveIntegerField(blank=True, null=True)),
                ('alco_days', models.PositiveIntegerField(blank=True, null=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_weeks_stat',
                                      to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField(null=False, blank=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profiletwoweekstat',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='profiletwoweekstat',
            unique_together=set([('user', 'date')]),
        ),
    ]
