# Generated by Django 2.2 on 2020-05-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0264_auto_20200321_1033'),
        ('srbc', '0267_auto_20200504_1055'),
    ]

    operations = [
    ]
