# Generated by Django 3.0.6 on 2020-05-30 12:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('crm', '0001_initial'), ('crm', '0002_auto_20180120_2113'), ('crm', '0003_campaign_is_open'), ('crm', '0004_campaign_is_admission_open'), ('crm', '0005_order'), ('crm', '0006_auto_20180217_1709')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('mailchimp_group_id', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('is_admission_open', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('expiring_at', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('dicount_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('payment_type', models.CharField(blank=True, choices=[(b'CLUB', 'Оплата участия в клубе'), (b'CHANNEL', 'Оплата участия в марафоне (заочный)'), (b'CHAT', 'Оплата участия в марафоне (очный)')], max_length=20, null=True)),
                ('days_paid', models.IntegerField()),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(choices=[(b'YA', 'Яндекс-Касса'), (b'PP', 'PayPal'), (b'MANUAL', 'Вручную')], max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[(b'PENDING', 'Ожидает оплаты'), (b'APPROVED', 'Оплачен'), (b'CANCELED', 'Отменен')], default=b'PENDING', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[(b'CLUB', 'Оплата участия в клубе'), (b'CHANNEL', 'Оплата участия в марафоне (заочный)'), (b'CHAT', 'Оплата участия в марафоне (очный)')], default='YA', max_length=100)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.DiscountCode')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
