# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 09:20


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0134_auto_20180219_1237'),
        ('crm', '0006_auto_20180217_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='days_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='wave_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_campaigns', to='srbc.Wave'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wave_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_campaigns', to='srbc.Wave'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('EUR', 'Евро')], default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.TextField(blank=True, null=True),
        ),

    ]
