# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 21:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180220_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[(b'YA', '\u042f\u043d\u0434\u0435\u043a\u0441-\u041a\u0430\u0441\u0441\u0430'), (b'PP', 'PayPal'), (b'MANUAL', '\u0412\u0440\u0443\u0447\u043d\u0443\u044e')], max_length=100, null=True),
        ),
    ]
