# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 21:36


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0135_auto_20180220_1220'),
        ('crm', '0008_auto_20180221_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wave_to_join', to='srbc.Wave'),
        ),
    ]
