# Generated by Django 3.1 on 2020-10-30 12:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srbc', '0200_auto_20201030_1542'),
        ('crm', '0010_auto_20180223_0840_squashed_0038_auto_20200321_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(blank=True, choices=[('YA', 'Яндекс-Касса'), ('PP', 'PayPal'), ('MANUAL', 'Вручную')], default='YA', max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PROCESSING', 'В обработке'), ('APPROVED', 'Оплачен'), ('CANCELED', 'Отменен')], default='PENDING', max_length=100)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('EUR', 'Евро')], default='RUB', max_length=3)),
                ('payment_type', models.CharField(choices=[('CLUB', 'Оплата участия в клубе'), ('CHANNEL', 'Оплата участия в проекте (заочный)'), ('CHAT', 'Оплата участия в проекте (очный)')], max_length=100)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('apple_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.applepayment')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.discountcode')),
                ('google_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.googlepayment')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbc.subscription')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbc.tariff')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wave_to_join_archive', to='srbc.wave', verbose_name='Payment wave')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='TariffHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Ожидается подтверждение платежа'), ('PAID', 'Оплачен')], max_length=40)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.payment')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srbc.tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_provider'], name='crm_payment_payment_6e0257_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='crm_payment_payment_65051f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['currency'], name='crm_payment_currenc_6cdf28_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='crm_payment_status_c1d8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='crm_payment_payment_5d0d66_idx'),
        ),
    ]
