# Generated by Django 3.1 on 2020-11-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20201030_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffhistory',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tariffhistory',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
