# Generated by Django 3.1 on 2020-11-02 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_auto_20201102_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffhistory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NOT_ACTIVE', 'Expired')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tariffhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
