# Generated by Django 3.1 on 2020-11-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0202_tariffgroup_is_wave'),
        ('crm', '0013_auto_20201102_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffhistory',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_history', to='srbc.wave'),
        ),
    ]
