# Generated by Django 3.1 on 2020-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_tariffhistory_wave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='tariffhistory',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
