# Generated by Django 3.1 on 2020-11-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20201109_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='active_payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.payment'),
        ),
    ]
