# Generated by Django 3.0.6 on 2020-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20201109_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariffhistory',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_history', to='crm.Payment'),
        ),
    ]
