# Generated by Django 3.1 on 2020-12-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20201110_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffhistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_history', to='crm.payment'),
        ),
    ]
