# Generated by Django 3.1 on 2020-12-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0205_auto_20201123_1139'),
        ('crm', '0018_auto_20201123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffhistory',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_history', to='srbc.tariff'),
        ),
    ]
