# Generated by Django 3.1 on 2021-01-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20201221_1426'),
        ('crm', '0019_auto_20201202_0958'),
    ]

    operations = [
    ]
