# Generated by Django 3.1 on 2021-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_merge_20210126_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('YA', 'Яндекс-Касса (банковская карта)'), ('PP', 'PayPal'), ('MANUAL', 'Вручную')], default='YA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('YA', 'Яндекс-Касса (банковская карта)'), ('YM', 'Яндекс-Касса (Яндекс.Деньги)'), ('PP', 'PayPal'), ('STRIPE', 'Stripe'), ('MANUAL', 'Вручную')], default='YA', max_length=100, null=True),
        ),
    ]
