# Generated by Django 3.1 on 2021-01-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0209_auto_20210119_1636'),
        ('crm', '0020_merge_20210119_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srbc.tariff'),
        ),
    ]
