# Generated by Django 3.1 on 2021-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_merge_20210119_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffhistory',
            name='valid_from',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tariffhistory',
            name='valid_until',
            field=models.DateField(db_index=True),
        ),
    ]
