# Generated by Django 3.1 on 2021-01-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20210126_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
    ]
