# Generated by Django 3.1 on 2021-02-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20210128_1435'),
        ('crm', '0022_auto_20210128_1023'),
        ('crm', '0021_application_tariff'),
    ]

    operations = [
    ]
