# Generated by Django 3.1 on 2021-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_merge_20210208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CLUB', 'Оплата участия в клубе'), ('CHANNEL', 'Оплата участия в проекте (заочный)'), ('CHAT', 'Оплата участия в проекте (очный)'), ('NON_WAVE', 'Оплата участия по подписке (доступ к митингам)')], max_length=100),
        ),
    ]
