# Generated by Django 3.1.7 on 2023-07-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20220319_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('add_advanced_payment', 'Добавление счета в продвинутом режиме'),), 'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
    ]
