# Generated by Django 3.1.7 on 2023-08-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20230728_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdamusPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('YA', 'Яндекс-Касса (банковская карта)'), ('YM', 'Яндекс-Касса (Яндекс.Деньги)'), ('PP', 'PayPal'), ('STRIPE', 'Stripe'), ('PRODAMUS', 'Prodamus'), ('MANUAL', 'Вручную')], default='YA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='prodamus_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.prodamuspayment'),
        ),
    ]
