# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 11:02


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0072_auto_20170723_1841'),
        ('content', '0021_auto_20170717_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgpost',
            name='wave_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srbc.Wave'),
        ),
    ]
