# Generated by Django 3.0.6 on 2020-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('content', '0023_auto_20170729_1949'), ('content', '0024_article_sort_num')]

    dependencies = [
        ('content', '0022_tgpost_wave_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgpost',
            old_name='wave_id',
            new_name='wave',
        ),
        migrations.AddField(
            model_name='article',
            name='sort_num',
            field=models.SmallIntegerField(blank=True, default=99),
        ),
    ]
