# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 16:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srbc', '0083_auto_20170819_2142'),
        ('content', '0024_article_sort_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('chat_type', models.TextField(blank=True, choices=[(b'CHAT', b'Chat'), (b'CHANNEL', b'Channel')], default=b'CHAT')),
                ('waves', models.ManyToManyField(related_name='chats', to='srbc.Wave')),
            ],
        ),
    ]
