# Generated by Django 3.0.6 on 2020-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_tgtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='audio_album',
            field=models.CharField(default='Лекции SRBC', max_length=144, verbose_name='Коллекция/альбом (для мобильного приложения)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='audio_author',
            field=models.CharField(default='Selfrebootcamp', max_length=144, verbose_name='Автор (для мобильного приложения)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='message_type',
            field=models.CharField(choices=[('QUESTION', 'Вопрос'), ('FEEDBACK', 'Отзыв'), ('MEAL', 'Рацион'), ('FORMULA', 'Формула')], max_length=100),
        ),
    ]
