# Generated by Django 3.0.6 on 2020-07-30 17:24

from django.db import migrations


def set_my_defaults(apps, schema_editor):
    TGTranslation = apps.get_model('content', 'TGTranslation')

    for key, (description, translation) in DEFAULT_TRANSLATION.items():
        TGTranslation.objects.update_or_create(
            key=key, defaults={'translation': translation, 'description': description}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20200618_1250'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_code=migrations.RunPython.noop),
    ]


DEFAULT_TRANSLATION = {
    'Q_NOTHING_FOUND': (
        "название кнопки 'Задать Вопрос' -> 'Ничего из перечисленного выше'",
        "Ничего из перечисленного выше"
    ),
    'Q_NOTHING_FOUND__TXT': (
        "сообщение при переходе в меню 'Задать Вопрос' -> 'Ничего из перечисленного выше'",
        "Пожалуйста, задайте вопрос команде"
    ),
    'Q_NOTHING_FOUND__SAVE_OK': (
        "Текст при корректном вводе сообщения в разделе 'Задать Вопрос' -> 'Ничего из перечисленного выше'",
        "Сообщение сохранено и будет передано команде. Спасибо!"
    ),
    'Q_NOTHING_FOUND_INPUT': (
        "служебная нода, не требует перевода",
        "Q NOTHING FOUND INPUT",
    )
}
