# Generated by Django 3.1 on 2021-01-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_add_tg_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting', name='type', field=models.CharField(
                choices=[('REGULAR', 'Большой митинг'),
                         ('NEWBIE', 'Новичковый митинг')],
                default='REGULAR', max_length=100),),
        migrations.RunSQL(
            sql='''
                UPDATE content_meeting set type='NEWBIE'
                WHERE type = 'NEWBY' 
            '''
        )
    ]
