# Generated by Django 3.1 on 2020-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_add_tg_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistemplate',
            name='adjust_carb_mix_vegs',
            field=models.NullBooleanField(),
        ),
    ]
