# Generated by Django 3.1 on 2020-08-18 21:16

from django.db import migrations


def set_my_defaults(apps, schema_editor):
    TGTranslation = apps.get_model('content', 'TGTranslation')

    for key, (description, translation) in DEFAULT_TRANSLATION.items():
        TGTranslation.objects.update_or_create(
            key=key, defaults={'translation': translation, 'description': description}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_add_tg_translations'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_code=migrations.RunPython.noop),
    ]


DEFAULT_TRANSLATION = {
    'CLIENT__NO_WAVE': (
        "Участник, без wave в профиле, нет доступа к боту",

        "К сожалению ваш тариф не позволяет нам общаться"
    ),
    'CAMPAIGN__NEAREST__UNDEFINED': (
        "В базе нет данных о следующей кампании",

        "К сожалению пока нет точной информации о дате следующего старта"
    ),
    'FUTURE_CLIENT__CAMPAIGN__NOT_CHANNEL': (
        "Будущий участникй, campaign привязан к ближайшей дате, формат участия != 'канал'",

        "Ваша учетная запись в проекте пока неактивна. Вы присоединились к старту {START_DATE}. В [личном кабинете](https://lk.selfreboot.camp) открыта оплата."
        " После оплаты учетная запись активируется автоматически. Желаем успеха! Если вы считаете, что произошла ошибка и учетная запись уже должна работать, пожалуйста, свяжитесь с командой проекта [в личных сообщениях страницы на Facebook](http://m.me/selfrebootcamp)."
    ),
}
