# Generated by Django 3.1 on 2020-12-21 11:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_analysistemplate_mixing_vegetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistemplate',
            name='add_fat',
            field=models.NullBooleanField(verbose_name='Добавить жиров'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_calories',
            field=models.BooleanField(default=False, verbose_name='Корректировка калорийности рациона'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_bread_late',
            field=models.NullBooleanField(verbose_name='Убрать хлеб из ужина'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_bread_min',
            field=models.NullBooleanField(verbose_name='Минимизировать хлеб'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_carb_vegs',
            field=models.NullBooleanField(verbose_name='Исключить запасающие овощи после обеда'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_mix_vegs',
            field=models.NullBooleanField(verbose_name='Смешивать овощи'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_sub_breakfast',
            field=models.NullBooleanField(verbose_name='Замена длинных углеводов на овощи(завтрак посхеме обеда)'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_fruits',
            field=models.CharField(blank=True, choices=[('NO', 'без дополнительных ограничений'), ('RESTRICT', 'ограничение фруктов'), ('EXCLUDE', 'замена фруктов')], max_length=20, null=True, verbose_name='Ограничение фруктов'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_protein',
            field=models.BooleanField(default=False, verbose_name='Корректировка белка в рационе'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='Текст анализа'),
        ),
    ]
