# Generated by Django 3.0.6 on 2020-12-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20201221_1429'),
        ('content', '0031_add_tg_translations'),
    ]

    operations = [
    ]
