# Generated by Django 3.1 on 2020-08-18 21:16

from django.db import migrations


def set_my_defaults(apps, schema_editor):
    TGTranslation = apps.get_model('content', 'TGTranslation')

    for key, (description, translation) in DEFAULT_TRANSLATION.items():
        TGTranslation.objects.update_or_create(
            key=key, defaults={'translation': translation, 'description': description}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_merge_20201229_2300'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_code=migrations.RunPython.noop),
    ]


DEFAULT_TRANSLATION = {
    'Q_BASE': (
        "Базовый узел при выборе пункта меню 'Задать вопрос'",

        "Задать вопрос"
    ),
}
