# Generated by Django 3.1 on 2021-01-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210115_1316'),
        ('content', '0034_add_tg_translations'),
    ]

    operations = [
    ]
