# Generated by Django 3.1 on 2021-02-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_merge_20210126_1622'),
        ('content', '0035_merge_20210119_1635'),
    ]

    operations = [
    ]
