# Generated by Django 3.1 on 2021-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_merge_20210208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistemplate',
            name='add_fat',
            field=models.BooleanField(null=True, verbose_name='Добавить жиров'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_bread_late',
            field=models.BooleanField(null=True, verbose_name='Убрать хлеб из ужина'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_bread_min',
            field=models.BooleanField(null=True, verbose_name='Минимизировать хлеб'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_carb_vegs',
            field=models.BooleanField(null=True, verbose_name='Исключить запасающие овощи после обеда'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_mix_vegs',
            field=models.BooleanField(null=True, verbose_name='Смешивать овощи'),
        ),
        migrations.AlterField(
            model_name='analysistemplate',
            name='adjust_carb_sub_breakfast',
            field=models.BooleanField(null=True, verbose_name='Замена длинных углеводов на овощи(завтрак посхеме обеда)'),
        ),
    ]
