# Generated by Django 3.1 on 2021-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210322_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='order_num',
            field=models.IntegerField(blank=True, default=99),
        ),
    ]
