from .admission_test_question import *
from .application import *
from .campaign import *
from .discount_code import *
from .payments import *
from .renewal_request import *
from .tariff_history import *
from .telegram_mail_template import *
from .user_admission_test import *
from .user_admission_test_question import *
